### ISSUE TITLE
Sending keys from repl to nyxt 

### ISSUE THREAD

**Issue by walseb** [atlas-engineer/nyxt#1000]
Hi! I want to be able to send keys directly from a repl to nyxt.
The method used by `fill-input-from-external-editor` (by pasting the text) works but it doesn't work in minibuffers. I'm thinking what might work is using `nyxt:ffi-generate-input-event`, but I can't construct a GDK key event and I haven't found any documentation on it. `gdk:make-gdk-event-key` seems to be it but I can't figure out how to format all the data it requires. Thanks for any help!

**Comment by Ambrevar** [comment]
First of all, let's raise a glass for the #1000 issue! :)
Hooray!

Input generation works but there is no good user abstraction for now.
For the minibuffer, you should be looking at the `insert` function.

More generally, look at `dispatch-input-event` to know how input is
handled.

Let me know if you need more details!

**Comment by walseb** [comment]
Thanks! `dispatch-input-event` seems to be what I want. But I can't figure out what to supply as the `event` parameter. It seems to be the same sort of C-struct that `nyxt:ffi-generate-input-event` expects (http://www.crategus.com/books/cl-cffi-gtk/pages/gdk_class_gdk-event-key.html) but I can't figure out how to translate the type description on that website to code. I'm very new to common lisp.

**Comment by Ambrevar** [comment]
Event generation is not well supported, but I did get it to work in the
past (up to Nyxt 1.5).

You don't need to generate events if you want to send the input to the
minibuffer.

You'd only need event generation if you want to send the input to the
web view.

Can you give me a precise example of what you'd like to achieve?

**Comment by walseb** [comment]
No I want it to both work in the minibuffer and on webpages. Although thinking about it now I could actually use `fill-input-from-external-editor` and the minibuffer `input` command depending on where I am, I will look into that.

The reason I want this is because I want to create a hydra layer for nyxt in emacs that emulates vim without the need to use vi-mode in nyxt. I want this because I have a bunch of binds in emacs to output custom characters either because they are easier to reach or they don't exist on my layout. 

I haven't gotten exwm to simulate keys but I used to bake this into nyxt using xdotool but it seems like nyxt has stopped responding to xdotool commands in later versions and besides it wasn't always 100% reliable, the minibuffer for example has always ignored xdotool commands (https://github.com/walseb/NixOSConfig/blob/9b4c9e7f975f6a98703db2af28b01c2d41e4b525/loose-configs/nyxt/init.lisp#L47)

**Comment by Ambrevar** [comment]
There are a few ways to implement hydra, but you don't need to generate
input if you don't intend the webview to actually process the keys.

Generate input is generally a bad idea.  Let's try to avoid it if we can.

Nyxt keeps the input keys in a `key-stack` slot.  This is something you
can leverage in many ways.

I have never used hydra myself, but here is a strategy that could work:

- Bind say "S-x" to "hydra-mode".  This mode could be a bit like
  application-mode and add a handler to the `current-keymaps-hook`.

  Or it could modify the input-dispatcher like
  `describe-key-dispatch-input` does.

- At this point, as long as the hydra-mode is on, pressing keys will
  only display a menu (e.g. the minibuffer or some Javascript overlay)
  with the association between the pressed bindings and the commands.

- When there is only a single command that matches, execute it and exit
  hydra-mode.



Note that Keys can be bound either to commands or to keymaps.  This
allows you to group bindings together.

For instance, you can create a FOO keymap that has "C-b" bound to
history-backwards and "C-f" to history-forwards.  Now you can create a
HYDRA-FOO keymap that has one binding, say "S-x" bound to the FOO
keymap.

Then S-x C-f and S-x C-b will do what you expect! :)



The minibuffer input is a bit special which is why some input methods
don't work.  Hopefully this will be fixed in the upcoming minibuffer
rewrite.

Does that help?


See also #178.

**Comment by aadcg** [comment]
Closed due to lack of feedback.
