### ISSUE TITLE
Unable to create a functional executable image using CCL

### ISSUE THREAD

**Issue by bqv** [atlas-engineer/nyxt#1057]
Processes tried:

In a CCL repl with nyxt and dependencies available, run `(asdf:load-system :nyxt/gtk-application)` and `(nyxt:start)`.
Success, nyxt starts and works

In an identical repl, run `(asdf:load-system :nyxt/gtk-application)` and `(ccl:save-application "nyxt" :prepend-kernel t :toplevel-function #'nyxt:start)`. Then run ./nyxt
Failure, with the following output:
```
> Error: The value #<A Dead Mac Pointer> is not of the expected type MACPTR.
> While executing: CLOSE-SHARED-LIBRARY, in process Initial(0).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip (possibly crucial) startup function GLIB::RUN-INITIALIZERS.
> Type :? for other options.
1 > q
Nyxt version 2
<INFO> [16:19:08] Loading Lisp file "~/.config/nyxt/init.lisp".
ERROR - Caught CCL::STREAM-IS-CLOSED-ERROR #<BASIC-CHARACTER-OUTPUT-STREAM :CLOSED #x3020003C81FD> is closed Removing #<LOG4CL-IMPL:TRICKY-CONSOLE-APPENDER #x300040BC808D> from #<LOGGER +ROOT+ #x300040BC7C0D>
;Compiler warnings for "~/.config/nyxt/init.lisp" :
;   <snip>
<INFO> [16:19:08] Listening to socket "~/.local/share/nyxt/nyxt.socket".
> Error: Can't resolve foreign symbol "g_idle_add_full"
> While executing: CCL::RESOLVE-EEP, in process toplevel(6).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
1 > 
> Error: Can't resolve foreign symbol "lfp_errno"
> While executing: CCL::RESOLVE-EEP, in process Anonymous thread(11).


;;;
;;; #<PROCESS Anonymous thread(11) [Active] #x302001F9387D> requires access to Shared Terminal Input
;;; Type (:y 11) to yield control to this thread.
;;;
```

On nix, of course.

**Comment by Ambrevar** [comment]
Note that CCL is not officially supported ;)

I've witnessed this issue as well, I believe it's due to a CFFI issue with
cl-cffi-gtk.
This is probably going to hard to fix.

My guess is that we are better off working on a new renderer that does
not rely on cl-cffi-gtk.

Out of curiosity, what's your reason for using CCL with Nyxt?

**Comment by bqv** [comment]
I prefer the ui/debug output of ccl, it's less noisy and easier to parse

**Comment by bqv** [comment]
> My guess is that we are better off working on a new renderer that does
> not rely on cl-cffi-gtk.

I wonder, would servo be a good fit? Or do you mean simply change the renderer bindings and add a new entire browser engine?

**Comment by Ambrevar** [comment]
Both! :)

I don't know the state of Servo, but if it's usable then why not!

We can work on WebKitGTK bindings leveraging cl-gobject-introspection.

Finally, we can update the currently broken QtWebengine renderers.  We
could also implement an alternative QtWebengine renderer that leverages
cl-gobject-introspection.

So many options :)

**Comment by bqv** [comment]
On further inspection, may be early days yet for servo...

**Comment by Ambrevar** [comment]
I've just managed to get CCL to start Nyxt!  It works with the new GI-based renderer. 

For now this renderer is not the default.  We are planning on making this the default renderer for 2.0.

To stat Nyxt with the new renderer,
load `nyxt/gobject/gtk` (_not_ `nyxt/gtk`), then run `(nyxt:start)` as usual.

Currently the GI renderer image is broken, it does not restart (some threading issue), but I'll work on a fix for 2.0.

Closing this since CCL should now work as well as SBCL (but still unofficially!).
Feel free to reopen if you have more questions.

**Comment by Ambrevar** [comment]
Re-opening since I realized that the issue was specifically about the image, not just running Nyxt from CCL.

**Comment by jmercouris** [comment]
Not in our scope.
