### ISSUE TITLE
Buffers are lost upon shut down and startup

### ISSUE THREAD

**Issue by mariari** [atlas-engineer/nyxt#1215]
**Describe the bug**
After closing and re-opening nyxt, all history of buffers are gone replaced by the default welcome screen.

**Precise recipe to reproduce the issue**
1. Open nyxt
2. open any website
3. Close nyxt
4. restart and load the session

At the end of this you should only see the startup screen.
**Information**
- OS name+version:
     - Arch Linux 
- Graphics card and driver:
- Desktop environment / Window manager name+version:
    - Xmonad 0.15 
- How you installed Nyxt (Guix pack, package manager, build from source):
    - make all from source  
- Information from command copy-system-information:

  If you can't run copy-system-information, please provide the following:
  - Nyxt version (from =M-x nyxt-version= or =nyxt --version=):
      - Version 2-pre-release-5-929-g16369384[ 
  - Lisp implementation/version (if built from source):
      - SBCL 2.1.1   
  - Kernel name+version:
  - WebKitGTK+ | QtWebEngine version:

**Output when started from a shell**

**Comment by Ambrevar** [comment]
I can't reproduce.
Maybe your history file is corrupted (we've had such issues already).

Can you try moving your `~/.local/share/nyxt/history/default.lisp` file see if fixes it for you?

If it does, could you share this file with us (assuming it contains no sensitive data) so that we investigate what state created the bug?

**Comment by jmercouris** [comment]
I already instructed this user to do that, but with no success :-/

**Comment by aadcg** [comment]
Stale.
