### ISSUE TITLE
Consistent file representation

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1454]
Currently, we have several file representations (this shot us in the foot in #1451):
- `file://` URLs (e.g., in `list-downloads`).
- namestrings.
- pathnames (e.g., in `file-source`).
- `data-path`-s (for persistence).

Maybe we should stick to at most two (URLs and `data-path`? pathnames and `data-path`?).

Alternatively, define `file-designator` (analogy: `url-designator`) and define `path` on it (analogy: `url`) to reliably get the path as a string.

**Comment by Ambrevar** [comment]
Also see discussion in https://github.com/atlas-engineer/nyxt/issues/1270#issuecomment-812848308.

I've investigated the issue for a while and finally discovered https://github.com/sionescu/iolib/issues/63.

Since we already use IOlib, we can go forward and start using iolib/pathnames all over the place.

iolib/pathnames are practically equivalent to native namestrings, so this would simplify everything a lot (no wildcard mess).

I suggest sending a patch that tries the following:
- Use IOlib instead of all `cl:pathname` and `uiop` calls.  In particular in `data-path`.
- Maybe limit the occurrences of `file://` to the strict minimum (i.e. when it must be passed to the renderer)?
- If it's not enough we really need more than just iolib/pathnames and `data-path`s, then implement the `file-designator`.

**Comment by Ambrevar** [comment]
I'll change the tags of this issue since this is a source of bugs and a rather important design matter.

**Comment by Ambrevar** [comment]
Marking as 3.0 since it's probably going to be backward incompatible and it's related to https://github.com/atlas-engineer/nyxt/issues/1270.

**Comment by Ambrevar** [comment]
Now that we have nfiles, this is more or less answered.

Namestring should be avoided.  We only every use them when:
- Printing to screen (e.g. in the prompt buffer)
- Passing to a library that does not support cl:pathnames, like IOlib.

My main concern: do we really need `file://` URLs?

**Comment by aartaka** [comment]
Well, xdg-open accepts `file://` URLs. Nothing else I can think of  ¯\\\_(ツ)\_/¯

**Comment by Ambrevar** [comment]
But it also accepts native-namestrings, doesn't it?

**Comment by aartaka** [comment]
Yes, it should :)

**Comment by Ambrevar** [comment]
See #2124 for a final fix.
