### ISSUE TITLE
CoverYourTracks by EFF makes the browser unresponsive

### ISSUE THREAD

**Issue by Kreyren** [atlas-engineer/nyxt#1475]
![image](https://user-images.githubusercontent.com/11302521/120916981-09bdaf00-c6ad-11eb-824d-3c94d3963089.png)

```console
kreyren@leonid:~$ nyxt --system | ix
http://ix.io/3oV0
```

### Steps to reproduce
0. Get `nyxt`
1. Open https://coveryourtracks.eff.org in `nyxt`
2. Run the test and expect browser to become unresponsive until killed

**Comment by Kreyren** [comment]
Invalid, seems to be caused by `torsocks`

**Comment by Ambrevar** [comment]
Please share the system information here directly, not on ix.io since it may become unavailable later.

About your issue: are you saying that running Nyxt with torsocks get it to crash?
What if you enable proxy-mode over Tor?  I personally use Nyxt over Tor all the time and it does not crash.

If a web process crashes, it should kill the buffer but it should not hang the program.
If it does, then it's a bug in Nyxt.

**Comment by Kreyren** [comment]
@Ambrevar Not a bug of nyxt, was caused by torsocks misconfiguration

**Comment by Ambrevar** [comment]
Can Torsocks crash applications?  Can you reproduce the crash with Epiphany?
