### ISSUE TITLE
Do-what-I-mean follow-mode in switch-buffer

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1491]
In commit b3dcf8400d92d1fe12eb91043981b52d5bc32201 @jmercouris changed the behaviour of `switch-buffer` to not move the last buffer to the top.

While this is convenient when follow-mode is on, it removes the ability to easily "alt-tab" between the last two buffers.

@jmercouris Can you remind me of the rationale behind not shuffling buffers?

**Comment by jmercouris** [comment]
There are a couple of problems:

1. invoking switch-buffers would shuffle the buffers, not showing you where you currently are
2. you immediately lose mental context when invoking switch-buffer as the page would immediately switch


1 is a problem because if you think about set-url it prefills with the current URL. People are used to the current element being shown first, and then being mutated.

**Comment by jmercouris** [comment]
Those may seem like the exact same problem twice, but they are slightly different. With point 1 above, I am trying to highlight that you don't want switch-buffers to actually change the recency of access for buffers.

**Comment by Ambrevar** [comment]
For future information, the discussion related to the initial issue is in #1430.
