### ISSUE TITLE
An activity tracker for Nyxt?

### ISSUE THREAD

**Issue by pdelfino** [atlas-engineer/nyxt#1493]
[pain]

Hi,

I have been using Nyxt on a daily basis for 4-weeks and I am really enjoying it!! =D

However, I really  miss one feature from my past web browser experience: an activity tracker. Historically, I used Firefox with the [Rescue Time ](https://www.rescuetime.com/)(RT) add-on. Recently, I have been trying a FOSS project called [Activity Watch](https://activitywatch.net/) (AW) which also has a Firefox extension.

I am still using RT and AW but since I am only using Nyxt and deleted Firefox now they only get relevant data about my "offline" activity. Thus, I lost the analytics on my web activity and I miss it. 

They even show how much time I spend on Nyxt **but I cannot see what I did _inside_ Nyxt**. They treat Nyxt _only_ as a desktop app.

**Comment by pdelfino** [comment]
[possible solutions] 

I see three possible approaches for this:

First, this could be a built-in feature like a component of the promising Nyxt's dashboard.

A second option woud be building a Nyxt extension. There are a few already.

A third option would be making a "coder partnership" with the Activity Watch project. This could be a good "marketing move"!

I think their user's might like Nyxt. And Nyxt user's might like the AW project. They already have Firefox and Chrome extensions available. Maybe we could build a Nyxt extension for them. Maybe the first third-party web-extension supported on Nyxt?

**Comment by aartaka** [comment]
Wow, that's a lot of cool ideas!

> First, this could be a built-in feature like a new component of the promising Nyxt's dashboard.
>
> A second option woud be building a Nyxt extension. There are [a few](https://github.com/atlas-engineer/nyxt/blob/master/documents/EXTENSIONS.org) already.


Dashboard should be extensible (although that's not yet the case), so writing a pluggable dashboard module sounds most intuitive there. For that we need to think of how to make dashboard easy to extend, though.

> A third option would be making a "coder partnership" with the [Activity Watch ](https://github.com/ActivityWatch/activitywatch) project. This could be a good "marketing move"!
> 
> I think their users might like Nyxt. And Nyxt's users might like the AW project. They already have Firefox and Chrome extensions available. Maybe we could build a Nyxt extension for them. Maybe the first third-party web-extension supported on Nyxt?

That sounds fascinating! No one of Nyxt developers uses Activity Watch, though :(

I'll mark this as help-wanted and maybe even try it myself in a month or two :) I hope it's not too much of a waiting for you...

**Comment by pdelfino** [comment]
I am glad you liked the idea, Artyom!

Actually, it would be really cool if I could help coding this. I am just not sure if it is too challenging on the technical side. If someone is willing to mentor me would be awesome.

I think I can do a humble prototype reading the history local file. At least counting which sites were visited.

[This](https://nyxt.atlas.engineer/article/the-thin-line-between-users-and-collaborators.org) article from @aadcg inspired me to post this here.

As he stated while quoting ESR:

> Every good work of software starts by scratching a developer’s personal itch.

**Comment by aartaka** [comment]
I am open to mentoring; and interfacing with third-party apps sounds interesting.

I'm hesitating, though... Maybe implementing even a subset of WebExtensions API (like [history API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs#history))  functions can help us run their Firefox/Chrome-targeting extensions? It's basically the same thing as with ad blocking — we don't really improve it because we hope to leverage existing solutions.

**Comment by aadcg** [comment]
Pedro Delfino ***@***.***> writes:

> This article from @aadcg inspired me to post this here.

I'm happy that such a seemingly useless and awkward article motivates
you!

This also leaves some food for thought for @jmercouris, since he
manifested scepticism towards the importance of the referred article
back then.

> Actually, it would be really cool if I could help coding this. I am just
> not sure if it is too challenging on the technical side. If someone is
> willing to mentor me would be awesome.

Feel free to write me if you feel the need.  I have, or used to have,
Nyxt wrapped around my head.

I had a cursory look about your background.  I think people who
deal/have dealt with maths and books from Elon Lages Lima have the
endurance to learn and accomplish their goals.  I've been there too, and
I even found a typo in one of his books
(https://math.stackexchange.com/questions/2549140/definition-of-meagre-set)!

At the end of the day, it's all about "bunda na cadeira" (to quote
Clóvis de Barros Filho) and finding a balance in the quest.  Boa sorte!

**Comment by jmercouris** [comment]
> I'm happy that such a seemingly useless and awkward article motivates you! This also leaves some food for thought for @jmercouris, since he manifested scepticism towards the importance of the referred article back then.

Well, sometimes things resonate differently with different people :-)

**Comment by Ambrevar** [comment]
In https://old.reddit.com/r/Nyxt/comments/oa69oe/whats_preventing_you_from_using_nyxt_as_your/ someone mentioned https://github.com/gildas-lormeau/SingleFileZ.  Maybe worth looking at.

**Comment by novoid** [comment]
> someone mentioned https://github.com/gildas-lormeau/SingleFileZ. Maybe worth looking at.

This was me.

SingleFileZ is more than just an add-on to log your web activity. It stores HTML files that are in fact containers that contain the whole content of visited web pages. This way, I get my whole browsing history in my archive (a few GB per month). If I want to re-visit some content, I may look up the local file and re-read the page even if the original page is gone.

Since my files follow a file name pattern like `2021-06-30T18.24.38 rise - github.com - An activity tracker for Nyxt_ · Issue #1493 · atlas-engineer_nyxt.html` (the file generated when I loaded this page) that starts with an ISO time-stamp which may be indexed by [this Memacs module](https://github.com/novoid/Memacs/blob/master/docs/memacs_filenametimestamps.org), all my web page visits end up in my Org mode agenda.

**Comment by Ambrevar** [comment]
To store HTML "containers", we could leverage Monolith.  See https://github.com/atlas-engineer/nyxt/issues/1063.

**Comment by gildas-lormeau** [comment]
@Ambrevar Out of curiosity, what makes Monolith more suited to your needs compared to SingleFile/SingleFileZ?

**Comment by Ambrevar** [comment]
If I understand correctly, SingleFileZ is a Firefox / Chrome / Edge extension, so Nyxt won't support it.
Monolith is a command line program, Nyxt can easily leverage it.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback. As written in in the description, SingleFile/SigleFileZ are Web Extensions and CLI tools.

**Comment by Ambrevar** [comment]
Oops!  I had overlooked that :p

Now the other issue I see with SingleFileZ is that according to the CLI README (https://github.com/gildas-lormeau/SingleFileZ/blob/master/cli/README.MD) is depends on NodeJS.

Is it possible to leverage SingleFileZ without the NodeJS dependency?

The NodeJS situation on Nix and Guix is still problematic, so we can't afford to have Nyxt depend on it at the moment.

**Comment by gildas-lormeau** [comment]
Technically, NodeJS is only used to pilot Pupeteer/WebDriver/Playwright/JSDOM... Thus, this code could be written in any other programming language able to inject scripts in a browser/webview. Heres'a an (obsolete) example of integration with a WKWebView on Mac for example: https://github.com/david-littlefield/SingleFileMac.

**Comment by Ambrevar** [comment]
Thanks for the link, this could prove very useful.

How would you compare Monolith and SingleFileZ?

**Comment by gildas-lormeau** [comment]
I would say the main difference is that Monolith is not using a browser under the hood so it cannot interpret JavaScript. That means that pages will be saved as if JavaScript was disabled. The other difference is the output format. SingleFileZ produces zip files disguised as self-extracting zip file.

**Comment by gildas-lormeau** [comment]
BTW, here's another link that could interest you https://github.com/zotero/zotero/blob/52932b6eb03f72b5fb5591ba52d8e0f4c2ef825f/scripts/babel-worker.js. It shows how Zotero integrates SingleFile in their product.

**Comment by jmercouris** [comment]
I don't think this is something that belongs in core Nyxt. Could be an extension some day.
