### ISSUE TITLE
QR Code generator (e.g. for URLs)

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1568]
Would be nice to have, popular browsers include this feature by default nowadays.

**Comment by Ambrevar** [comment]
See https://quickref.common-lisp.net/cl-qrencode.html.

**Comment by Ambrevar** [comment]
And https://ag91.github.io/blog/2021/06/29/extending-nyxt-via-emacs-how-to-leverage-common-lisp-wealth-to-get-your-links-as-qr-codes/.

**Comment by jmercouris** [comment]
This is a really cool idea, I like it!

**Comment by novoid** [comment]
@jmercouris May I ask why this issue got closed?

As far as I understood, the blog article mentioned by @Ambrevar generates a (PNG) file in the file system but no QR code is shown within Nyxt as the original request contained: (1) invoke a command or button (2) a QR Code is shown on screen in order to be scanned by any device with a camera.

**Comment by jmercouris** [comment]
@novoid Sorry for the confusion, on master it does work! Try `show-qr-code-of-current-url`.

**Comment by jmercouris** [comment]
It will generate a QR code AND show it, and you can scan it :-)
