### ISSUE TITLE
Add `toggle-buffers-panel` and `toggle-bookmarks-panel` commands

### ISSUE THREAD

**Issue by edgar-vincent** [atlas-engineer/nyxt#1628]
I think users would expect to be able to toggle the visibility of the buffers- and the bookmarks-panel with a single keybinding, for instance.

**Comment by Ambrevar** [comment]
We have `show-buffers-panel` which already toggles the panel.
Is that what you want?

@jmercouris I think we should rename both panel commands to `toggle-*-panel`.  Thoughts?

**Comment by jmercouris** [comment]
No, I don't think we should rename them because invoking the command again should not toggle the panel, but in fact refresh the panel. Consider list-buffers. If you invoke list-buffers twice in a row, you get a refreshed version of the list-buffers.

**Comment by jmercouris** [comment]
That said, we /could/ make another command called `toggle-*-panel` that toggles the panel. Maybe we can introduce a macro that automatically generates it.

**Comment by Ambrevar** [comment]
Oh, right, I missed that.

Indeed, it looks like it's time for a command-generating macro!

**Comment by aaron-tan** [comment]
Hi, @Ambrevar @jmercouris could you elaborate on what the feature you want implemented is? I'm pretty new to contributing and I'm happy to work on this I'm just not exactly sure what the feature is supposed to be.

Also, I believe what the original commenter of this issue is talking about is that there is a`show-buffers-panel` but there doesn't seem to be a way to toggle it off? It seems that once you run the `show-buffers-panel` command it stays on and doesn't go away unless you close the window and restart Nyxt.

Could we add say a command that closes this panel? Like a `hide-buffers-panel` command or `hide-bookmarks-panel` command. It would be a useful feature to have I think.

**Comment by Ambrevar** [comment]
There is `delete-panel-buffer`, I think that should do what you asked.

Is it a good idea to have a toggle though?
Currently, calling a panel command multiple time refreshes it, which is
handy.
Would it be better to toggle it instead?  If we did, we could
effectively refresh by calling the toggler twice.

Thoughts?

**Comment by edgar-vincent** [comment]
`delete-panel-buffer` 1) opens the prompt buffer and 2) is a separate command. Both 1 and 2 don't make it easy to (1) quickly show and hide the panel-buffer with a  (2) single keybinding.

Would `toggle-*` commands be desirable in addition to the current commands? One could call `show-*-buffer` to show or refresh the buffer, `delete-panel-buffer` to select which one one wants to delete and `toggle-*` for quick operations.

**Comment by jmercouris** [comment]
@edgar-vincent That sounds about right, I think we are all on the same page here :-)

**Comment by jmercouris** [comment]
Will do soon (tm)

**Comment by jmercouris** [comment]
Done!

7829dbb7
