### ISSUE TITLE
Tile buffers

### ISSUE THREAD

**Issue by Kabouik** [atlas-engineer/nyxt#1639]
An exciting bug I got today:

![](https://user-images.githubusercontent.com/7107523/126225755-ee39a681-70f2-4d83-84fd-871a5ea606ab.png)

Two different buffers were showing at the same time, and they could both be controlled independently, so that almost felt like a fully-working feature! Stacking vertically as in the screenshot would probably not be so useful on most screens, but horizontal tiling of up to three buffers could work.

I believe the bottom buffer eventually vanished when I hit `<Esc>`, so I assume that somehow a web-buffer was displayed instead of the prompt buffer when I pressed `<C-space>` before.

I wouldn't have dared asking for a feature like that before, thinking it would be quite a lot of work and far down in the priority list, but seeing it appearing all by itself made me wonder.

**Comment by jmercouris** [comment]
Oh, this is /very/ high on my priority list. Ever since I tried it in the REPL. In fact we have been slowly making provisions for this to become possible. I would really like to see this done!

It is just named as `window-splitting`: https://github.com/atlas-engineer/nyxt/issues/55

First we must fix the bug here: https://github.com/atlas-engineer/nyxt/issues/1604

and then it shall be possible. What remains is deciding on the data structure and interface...

Probably we will implement a `manual` tiling interface like Emacs, Tmux, etc.

**Comment by jmercouris** [comment]
Somehow seeing the screenshot makes it feel that much closer, and that much more motivating to get it working!

**Comment by Kabouik** [comment]
Excellent, manual tiling interface sounds great too! I'm sorry I missed #55, I only searched on the terms "buffers" and "tile" or "tiling".

**Comment by aartaka** [comment]
Closing in favor of #55.
