### ISSUE TITLE
Goto link-hint after a certain time without pressing enter

### ISSUE THREAD

**Issue by swedebugia** [atlas-engineer/nyxt#164]
In the past I used a plugin for firefox that enabled me to adjust the time in msec before following a link-hint.
Is this possible in next?

**Comment by Ambrevar** [comment]
Everything is possible with Next! :)

**Comment by jmercouris** [comment]
@Ambrevar I've been thinking we should make something like this: https://html5zombo.com for Next :D

**Comment by Ambrevar** [comment]
@jmercouris: ?!?!? :D

**Comment by alexherbo2** [comment]
I don’t like to add a timer.  The real issue is more about to validate link hints without pressing <kbd>Enter</kbd>, when the hint is completed.

**Comment by 4t0m** [comment]
Currently it looks like the plan is to have a hint-completion-fn that also fuzzy searches over the text and url of the links, in which case you can't just follow the hint upon completion.

The other issue mentions a setting to complete minibuffer selection when there is only one matching result, which would address this in cases where there are no matches with the titles/urls of links on the page.

It makes sense to me to also have a way to follow hints that doesn't do a fuzzy search over all of this additional text, since I quite like the behavior of vimium/qutebrowser.

**Comment by alexherbo2** [comment]
I’d like to keep the hint behavior simple too.  Mixing hints + fuzzy search in the same UI does not sound good.

**Comment by Ambrevar** [comment]
The timer can be made optional.

> It makes sense to me to also have a way to follow hints that doesn't
> do a fuzzy search over all of this additional text, since I quite like
> the behavior of vimium/qutebrowser.

We can have to classes of "hints": the visible ones and all of them.

**Comment by alexherbo2** [comment]
Even optional, we should avoid to use timers at all.

**Comment by Ambrevar** [comment]
I don't really get timers either, but it was suggested at least twice, I
guess some users like it.

**Comment by aartaka** [comment]
734e38fabfed955152d8943ffdef83c2a1038fe8 should do the trick, shouldn't it?

**Comment by aartaka** [comment]
Closing, as the functionality is there already. Feel free to reopen if there's something I missed :)

**Comment by jmercouris** [comment]
> @jmercouris: ?!?!? :D

One of the things said on Zombocom is "Anything is possible on Zombocom", so it seemed a perfect time to bring it up! :-)
