### ISSUE TITLE
But why?

### ISSUE THREAD

**Issue by shrinidhi111** [atlas-engineer/nyxt#1711]
What are the use cases of this project?

Is it trying to create a new engine (in which case it's a noble pursuit, now that chromium has taken over the world...)

But why CLI only? Is GUI support in development or its forever keyboard only?

Is it useful for some kind of automation? 

What are all the ways this project is useful and has been useful for you?

**Comment by edgar-vincent** [comment]
[Please note that I am not a Nyxt developer, only a user, and this comment does not necessarily reflect the team's views.]

Nyxt is not (for the moment) creating a new rendering engine. It currently relies on Webkit, but is designed to be engine-agnostic. It had support for WebEngine (Blink) until version 1.5. Reliance on Servo is not yet technically easy enough, but it might be in the future.

There might be a confusion of terms regarding "CLI". Nyxt does not have a command-line interface, but a graphical (GTK) interface. It is however keyboard-centric, which is one of its _raisons d'être_. It is very much usable with a mouse, though.

Nyxt's main strength is the fact that it is extensible. Being written in Common Lisp, its source code can be redefined on-the-fly via a REPL, be it internal (`repl-mode`) or external (with Emacs and Sly/Slime). It is also, as far as I know, the only browser which somehow mimics Emacs' interface (prompt-buffer, modes, commands, etc.) to quite an advanced level, which some of us find appealing. Have a look at the [articles](https://nyxt.atlas.engineer/articles) Atlas has published about Nyxt. They demonstrate some of Nyxt's features and provide practical examples.

**Comment by aadcg** [comment]
Emacs + Browser could be replaced with Nyxt alone.  In theory, Nyxt could be a computing environment just like Emacs is.  Would it replace Emacs completely?  For most cases, when you have a GUI session.  If you're doing your computing from a tty, Emacs would still be the way to go.

Nyxt acknowledges that HTML + CSS + JS, sadly, won. But Nyxt says "Ok, it won but I don't want to give on the Emacs way".

Let's focus on the present.  I'll share my very personal views.  

Does Nyxt replace a reliable browser like Firefox?  No.  Will I buy a train ticket with Nyxt?  No.  In fact, I don't know what I can expect from it security wise.   Will I be able to use Nyxt for video calls?  [Not yet.](https://github.com/atlas-engineer/nyxt/issues/737)  Will I use it as a text editor, IDE, etc?  No, because Emacs exists and does a much better job.  Why would I go from Emacs + Browser to Emacs + Nyxt + Browser?  Indeed, I don't use Nyxt.  

It can be argued that Nyxt does a better job than most browsers do.  Here would come the thesis of the "power users".  But these seem to be extremely confused people.  Sadly, the developers too have their priorities twisted.  They aim for these fancy, "power user" features. In fact, generally speaking, I think the developers don't understand Emacs.  Emacs isn't a termo nuclear power station. Emacs enables you to build one, IF THEY WANT. In short,  [I'm in search of reality, not hyper-reality](https://yewtu.be/watch?v=x73MNvENQr8). Simple, dumb and well-tested blocks let you compose as you wish. I wish Nyxt would focus on keys issues (#1169, #1204, #1677, etc).  Or distributed REAL features to its users (#1246). Yet countless useless functionality continue to pop up.  It might impress some, but not me. Proper documentation would impress me (it would put to the naked eye countless inconsistencies, that's probably why no effort goes into it).

I took the time to share my thoughts because I still think that Nyxt is an interesting idea. And I have respect for all of the work developed.  These people are putting all of their energy on it.  Thank you.

**Comment by edgar-vincent** [comment]
Have we answered your questions, @shrinidhi111? Can this issue be closed?

**Comment by jmercouris** [comment]
Please feel free to reopen if there is something we missed. Thank you everyone for chiming in :-)
