### ISSUE TITLE
history-tree leaks history to hard drive

### ISSUE THREAD

**Issue by shamazmazum** [atlas-engineer/nyxt#1717]
When you call `history-tree` command in `nosave-buffer`, the history is leaked to the hard drive.

**Precise recipe to reproduce the issue**
1. Remove `~/.local/share/nyxt/history` (or where else your history is stored) for a clean experiment.
2. Open some page on the net in `nosave-buffer`. Follow some links
3. Look at the history by calling `history-tree`.
4. Kill history buffer.
5. Now your history is leaked to the hard drive. You can check `~/.local/share/nyxt/history/default.lisp`.

**Information**
- OS name+version: Irrelevant
- Graphics card and driver: Irrelevant
- How you installed Nyxt (Guix pack, package manager, build from source): I am on commit `af599d8`. All dependencies are installed via ultralisp.
- SBCL 2.1.7

Maybe all internal buffers must behave like `nosave-buffer` (i.e. make a `nosave-mixin` class and inherit `nosave-buffer` and `internal-buffer` from it)?

**Comment by aartaka** [comment]
Yes, I can reproduce it.

**Comment by Ambrevar** [comment]
While investigating this issue, I noticed something else.  If I start Nyxt using a non-default data-profile, such as "dev" as per the manual, then the `nosave` data-profile is still "based" on the default profile.
As a result, `expand-data-path` is specialized against the default profile and not the "dev" profile, which results in `nosave` buffers expanding their data paths to the defaults ones instead of the "dev" ones.

This is probably unexpected behaviour, one would expect the default profile to be replaced everywhere, not just in regular buffers.

**Comment by Ambrevar** [comment]
I believe we should also fix the cookies leak with nosave buffers, if any, as reported here: https://github.com/atlas-engineer/nyxt/pull/1716

**Comment by Ambrevar** [comment]
Should be fixed with #2072.
