### ISSUE TITLE
libraries/keymap: Allow rebindings non-prefix keys to be prefix keys in child keymaps

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#1871]
In #1858, I discovered that if you bind `C-x` in CUA keymap, you can no longer use any `C-x`-prefixed command in Emacs/VI keymap. I believe that this is not the behavior one can expect there: child keymaps, when using parent non-prefix keys as prefix ones, should have a priority. 

In other words, even it `C-x` is defined in CUA, it should never work without a subsequent key (like Emacs' `C-x C-f`, for example) if Emacs mode is on.

**Comment by Ambrevar** [comment]
Should it really be 3.0?  I know it would change the API but only slightly and it was unspecified behaviour, so I guess it's fine to fix this on 2-series too, no?

**Comment by aartaka** [comment]
> Should it really be 3.0? I know it would change the API but only slightly and it was unspecified behaviour, so I guess it's fine to fix this on 2-series too, no?

Yes, makes sense :)

**Comment by jmercouris** [comment]
A very salient observation. I guess this behavior occurs due to the inheritance of keymaps! Perhaps there should be a way to reorder the inheritance hierarchy of keybindings as we previously discussed. OR, a way to change the priority of a given keymap.

**Comment by Ambrevar** [comment]
Absolutely, I'm guessing it's a 1-sexp-patch!

**Comment by Ambrevar** [comment]
I've investigated this and found out that the behaviour is actually what's suggestion in the original post.

If you set `C-x` to `'cut` in `'web-mode`, `C-x h` works as expected in `emacs-mode`.

Note that `C-x C-x` resolves to `nil` (unbound indeed) which forwards the key to webkit and triggers a text cut, since it's a default WebKit binding.

Finally, the reason why `C-x C-f` is shadowed is because it's part of the `base-mode` keymap, while `C-x` bound to `'cut` is in web-mode.

The binding lookup works in a bidimensional fashion.  It first browses the keymap `parent schemes`, then the keymap `parents`.

Does that make sense?  If so, then this is a non-issue, but maybe we can do something about the `C-x C-f` binding nonetheless.  Any suggestion?

**Comment by Ambrevar** [comment]
My bad, there is a bug indeed: the prefix keys are only collected from the current keymap and not from the parents.

**Comment by Ambrevar** [comment]
Fix sent at #1900.

**Comment by jmercouris** [comment]
I see. What about this some sort of "escape key" for a single binding passthrough invokation. I can imagine typing in "ESC" and then typing in "C-x" and having it forward just "C-x" to the renderer. A bit tangential to the original post, but an idea I had.

**Comment by Ambrevar** [comment]
We've already discussed something related to a passthrough prefix in https://github.com/atlas-engineer/nyxt/issues/1635 and https://github.com/atlas-engineer/nyxt/pull/1652.

For now, `C-z` toggles passhthrough, so `C-z C-x C-z` passes `C-x` to the renderer.  Should we really have a 1-shot passthrough shortcut?  Maybe indeed.

That said, how is this related to the issue at hand @jmercours ?  Misunderstanding ?

**Comment by jmercouris** [comment]
It's not related, hence why I said it was a tangent :-D

**Comment by mariari** [comment]
It seems the [commit that got pushed](https://github.com/atlas-engineer/nyxt/commit/d5b1204860ae58c6c490231b06837f764d61084b) creates issues in setups where multiple keymaps are wanted. Namely with having both `emacs` and `vi` enabled. You end up with the first key map winning out, with no fallback behavior. Thus

although `j` is unbound in `emacs` mode, (`C-h k j` ---> "Unbound: "j" [#44]), it does not dispatch it to the lower `vi-normal-mode` . Meaning that multiple modes can not be had at once

**Comment by Ambrevar** [comment]
I can reproduce this before the aforementioned commit.  @mariari, are
you sure this wasn't a problem before that too?

**Comment by mariari** [comment]
> I can reproduce this before the aforementioned commit. @mariari, are you sure this wasn't a problem before that too?

Yeah, I probably wasn't clear in how I worded things, but the `emacs` before `vi-normal` seems to be an issue even before this patch. I've always had emacs mode implicitly on, and thus the fallback behavior worked in my favor wtih just the explicit `vi-normal`. 


Would be best if there was a proper solution to this rather than rolling back any changes made here

**Comment by Ambrevar** [comment]
What you are describing might come from a misunderstanding: the
vi-normal _scheme_ (not keymap) inherit from the emacs _scheme_.

When vi-normal-mode is enabled, it sets the current buffer scheme name
to `vi-normal`.  Bindings are first looked up in the vi-normal map, then
in the emacs map if there was no match.

If you enable emacs-mode on top, it _replaces_ the current buffer scheme
name, so it's as if vi-normal-mode was not enabled at all!
And since the `emacs` scheme does not inherit from `vi-normal`, the VI
bindings are completely ignored.

Does that make sense?

I know it can be confusing, most importantly because the vi-normal-mode
is still enabled.  This is an important design issue, but it's not
trivial to fix.  Any suggestion ?

@jmercouris @aartaka @pdelfino @guojing0

**Comment by mariari** [comment]
> What you are describing might come from a misunderstanding: the vi-normal _scheme_ (not keymap) inherit from the emacs _scheme_. When vi-normal-mode is enabled, it sets the current buffer scheme name to `vi-normal`. Bindings are first looked up in the vi-normal map, then in the emacs map if there was no match. If you enable emacs-mode on top, it _replaces_ the current buffer scheme name, so it's as if vi-normal-mode was not enabled at all! And since the `emacs` scheme does not inherit from `vi-normal`, the VI bindings are completely ignored. Does that make sense? I know it can be confusing, most importantly because the vi-normal-mode is still enabled. This is an important design issue, but it's not trivial to fix. Any suggestion ? @jmercouris @aartaka @pdelfino @guojing0

I see, I assumed when keymap inheret talks were being mentioned, that it was sort of a list of modes that were enabled, with an ordering that allowed proper shadowing of keys to occur.

**Comment by Ambrevar** [comment]
> I see, I assumed when keymap inheret talks were being mentioned, that
> it was sort of a list of modes that were enabled, with an ordering
> that allowed proper shadowing of keys to occur.

This is the logic indeed for regular modes, but emacs-mode and
vi-normal-mode are special in the sense that they set the current buffer
scheme.

Maybe they should not be modes then?
