### ISSUE TITLE
Is there Sandboxing?

### ISSUE THREAD

**Issue by Profpatsch** [atlas-engineer/nyxt#188]
Searching through the github repo, I can’t find any mentions of the word “sandbox”.

Sandboxing is a pretty important feature of modern browsers, preventing the Javascript code of one tab to access another, or to access e.g. the file system.

Is there sandboxing in NEXT, comparable to other mainstream browsers (Chromium, Firefox), and if so, what are the security guarantees compared to those browsers?

**Comment by Ambrevar** [comment]
Sandboxing is coming to WebKitGTK.
(https://webkitgtk.org/2018/11/22/webkitgtk2.23.1-released.html.)

I think the macOS version already has sandboxing.  @jmercouris ?

Another way to go on GNU/Linux / *BSD would be that package maintainers sandbox
the next-gtk-webkit executable.  This would probably scale better than having
all security sensitive programs re-inventing their own sandboxing every time.

Thoughts?

**Comment by jmercouris** [comment]
macOS, indeed has sand boxing, ditto on what ambrevar said about regarding webkitgtk

**Comment by Ambrevar** [comment]
Update: Sandboxing will be included with WebKitGTK 2.26.
We will also be able to enable it on the QtWebengine platform port.

**Comment by vindarel** [comment]
We can also run Next in a Firejail sandbox: https://github.com/atlas-engineer/next#run-next-in-a-security-sandbox

**Comment by Ambrevar** [comment]
Sandboxing is now in WebKitGTK 2.26!

**Comment by Ambrevar** [comment]
Not quite subprocess sandboxing, but commit  a785e2de12d030fb30ac892530e2814c43f5d5b6 explains how to start Next in a Guix container which adds a (reproducible) security layer between Next and the rest of the system.

**Comment by travankor** [comment]
https://blogs.gnome.org/mcatanzaro/2020/03/31/sandboxing-webkitgtk-apps/

**Comment by Ambrevar** [comment]
I read this article too, the problem is that it crashes Nyxt when we
turn it on :(
This needs more investigation, but it won't be an easy fix I'm afraid.

**Comment by solna86** [comment]
I'd like to say that sandboxing (with per-tab containers) is the only major thing that prevents me from migrating from Firefox to Nyxt.

Sadly, given how privacy is treated on the web these days, I think the only viable way to protect yourself is to have per-domain isolation. Otherwise, cookies leak.

Firefox does this particularly well with the Temporary Containers addon, which simply creates self-destroying containers for each new domain. I'm sure implementing this in Nyxt is pretty easy once per-tab sandboxing is working?

**Comment by Ambrevar** [comment]
Note there are 2 features we are talking about here:

- process sandboxing: this is actually just a matter of ticking an
  option in WebKitGTK.  Sadly it doesn't work yet, I presume because of
  FFI issue.  I'd like to work on this at some point, possibly with the
  new cl-gobject-introspection renderer.

- per-buffer isolation: This we already support but we lack a good user
  interface.  @aartaka is working on it.

  You can start playing with the =request-resource-hook= to spawn a new
  buffer with a new cookie file on each domain for instance.

**Comment by solna86** [comment]
Thanks for your prompt reply @Ambrevar.

It's great to hear both features are already in progress.

Perhaps it'd be useful to open an issue / milestone with a list of privacy & security items required to achieve feature parity with major browsers?

**Comment by Ambrevar** [comment]
We have this issue tracker and the ChangeLog file.
Wouldn't fit in one of these two?

I could add a "privacy" tag to related issues, what do you think?

I'd rather not add yet another list to the project ;)

**Comment by solna86** [comment]
Sure @Ambrevar, apologies for the late reply.

I just meant it'd be nice to have a little checkbox either in one of the issues you already have open or in a new issue that would serve as a "metaissue" for all basic privacy features that gets closed when nyxt implements these.

So nothing new. Something within the Issues list you already have.

**Comment by Ambrevar** [comment]
Thanks for your feedback.

I've added a `security` tag to this issue.  You can get the list of security-related issues by following this link:
https://github.com/atlas-engineer/nyxt/labels/security

I'll add a privacy tag to the relevant issues.

**Comment by jmercouris** [comment]
I ran a test again with GI. Sandboxing does work, but is incredibly unstable and does not like javascript. I recommend leaving it unchecked for now.

**Comment by Ambrevar** [comment]
Actually the problem is not with WebKitGTK but with us.
We need to fix it before 2.0.

**Comment by Ambrevar** [comment]
Thanks for testing by the way.
Too bad it's bad news :p

**Comment by jmercouris** [comment]
We do not need to fix it before 2.0.0 as it does not break API

**Comment by jmercouris** [comment]
To expand upon this:

2.0.0 is not meant to be an absolute panacea to the problems browsers face. We will have to iterate a lot yet! I think we will maybe get close to our vision by version 5.0.0.

I think we need to freeze the features and problems, otherwise, we may feasibly never release 2.0.0. There is always more to be done in the pursuit of perfection.

Lastly, sandboxing is (in my opinion) an operating system level concern. You should use jails, containers, and other mechanisms to restrict the access of your programs.

**Comment by Ambrevar** [comment]
Sandboxing (in the web browser context) is not the same as
containerizing, so it's not an OS issue.

Sandboxing happens _within_ the browser context, between the various
WebKit instances.

See
https://blogs.gnome.org/mcatanzaro/2020/03/31/sandboxing-webkitgtk-apps/
for a better introduction and some convincing arguments.

It's a critical security feature, so not having it for 2.0 would be a
bummer which would probably get us a bad reputation.

We are doing wrong with JavaScript, so my guess is that fixing it could
be as simple as fixing the JavaScript calls.

**Comment by jmercouris** [comment]
It is not OUR javascript calls that break things. I think (have not verified), that it is Javascript calls by DuckDuckGo and others.

**Comment by Ambrevar** [comment]
Epiphany and other WebKitGTK browsers work well with sandboxing.
Maybe there is a binding issue, but since even GI fails here, I don't know.
This requires more investigation.

**Comment by q3cpma** [comment]
Would be nice to have an official firejail profile at some point; maybe one for webkit and one for qtwebengine?

**Comment by Ambrevar** [comment]
Yes, that would probably be a good idea!

I don't use firejail myself, so would you be interested in contributing
a profile?

**Comment by jmercouris** [comment]
Sandbox is now enabled on master! It works. I discovered that the problem was in trying to set the sandbox AFTER the context was assigned to a web view. Additionally, we were using a singular web context (which does not work).

Everything is all well now!

**Comment by jmercouris** [comment]
Therefore there were two issues! Intertwined!

**Comment by Ambrevar** [comment]
Fantastic!

> Additionally, we were using a singular web context (which does not work).

I'm confused: 91f5f3efd444db8e28208ad9cca8b33ccdac82ea only enables
sandboxing,  it does not change the number of web context.  Can you clarify?

**Comment by jmercouris** [comment]
In the past, when we tried to enable sandboxing, I believe we were using a singular context.

**Comment by Ambrevar** [comment]
But
https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebContext.html#webkit-web-context-set-sandbox-enabled
does not mention this, and in fact many WebKitGTK-based browsers use a
singular context, so I'm not sure it's an issue.

I'm also pretty sure that I correctly enabled sandboxing before anything
else when I had tried.

So maybe something else fixed it.  Anyways, good thing it's working!

**Comment by jmercouris** [comment]
I do not believe the Official documentation for even a second! 11 :-D
