### ISSUE TITLE
Increase dynamic space size for .deb and in makefile

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#1946]
SBCL default dynamic space size varies across installation.

I suggest we set it to 3 GiB by default, it may fix some issues like the one reported by @jmercouris in https://github.com/atlas-engineer/nyxt/pull/1940#issuecomment-996929347.

Thoughts?

**Comment by aartaka** [comment]
> I suggest we set it to 3 GiB by default

I'm always confused by SBCL docs regarding the `--dynamic-space-size`, as it says something about per-thread space. Because of that and because of the potential RAM usage restrictions (Windows restrictions in particular, as described [in the comments to this StackOverflow question](https://stackoverflow.com/a/7181683)), I suggest using something between one and two gigabytes.

**Comment by jmercouris** [comment]
The number 2048 appeals to me, I think we should use that :-)

**Comment by Ambrevar** [comment]
I've hit errors twice in the past where I was pushed to set it 3 GiB
instead of two.

What we can do is take the mininum between the current dynamic space
size and 2 GiB, this way we ensure that we don't lower it.

**Comment by aartaka** [comment]
> What we can do is take the mininum between the current dynamic space size and 2 GiB, this way we ensure that we don't lower it.

You mean maximum? If so, that sounds sane :D

**Comment by Ambrevar** [comment]
Yes, maximum !

**Comment by Ambrevar** [comment]
Should be fixed in #1984, what do you think?
