### ISSUE TITLE
Default auto-mode rules?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2004]
There are often URLs that would only work well if some modes are enabled. Think .onion URLs — unless one is using system-wide proxy, `proxy-mode` is a must.

Another example is #1994: all `gopher:` URLs should have `gopher-mode` enabled for them.

I believe it could be convenient if we provide some `auto-mode` rules by default. Obviously, they will be there in the `auto-mode-rules.lisp` file so that one can disable those.

Does that make sense?

**Comment by guojing0** [comment]
Do you mean that if Nyxt detects `.onion` URLs, then `proxy-mode` is enabled before loading these URLs? Similarly, if the URL starts with `gopher:` then `gopher-mode` is enabled before loading said page?

**Comment by aartaka** [comment]
Yes, that's what I mean. Good starting point for .onion URLs could be [this post on the forum](https://discourse.atlas.engineer/t/tor-v3-onion-address-auto-mode-rule/395).

**Comment by hendursaga** [comment]
For onion addresses, a good idea might be to specialize the proxy-mode class, with just the Tor proxy configured. I would also add support for [Lokinet](https://lokinet.org/) addresses, too, with the same idea.

**Comment by hendursaga** [comment]
Naturally, eventually this should include support for [I2P](https://geti2p.net/en/) and [GNUnet](https://www.gnunet.org/en/) addresses, along with whatever other "alternative" Internet protocols there are.

**Comment by Ambrevar** [comment]
I found out another critical issue: start the `lisp-repl`, evaluate `*browser*`, click on the link.  You are now in the help buffer of `*browser*`, but you are still in `repl-mode`! :/ 

@aartaka Thoughts on this?

Actually if we had major modes, the issue would be fixed in this case and in all the aforementioned cases.  What do you think?

Another fix is to remember modes in history, but then we've got to make the distinction between modes that were automatically enabled and those that were enabled by the user.

**Comment by aartaka** [comment]
> I found out another critical issue: start the `lisp-repl`, evaluate `*browser*`, click on the link. You are now in the help buffer of `*browser*`, but you are still in `repl-mode`! :/

Indeed, that's a quirky one 0_o

> Actually if we had major modes, the issue would be fixed in this case and in all the aforementioned cases. What do you think?

Yes, that sounds sane. I guess there was enough of precedents to finally get to major modes :D 

> Another fix is to remember modes in history, but then we've got to make the distinction between modes that were automatically enabled and those that were enabled by the user.

That seems to duplicate `last-active-modes` of `auto-mode`, so I'm not sure.

**Comment by Ambrevar** [comment]
> That seems to duplicate `last-active-modes` of `auto-mode`, so I'm not
> sure.

I'm not sure either, but one thing for sure is the following: we need to
draft a plan for

- major-modes (or not)?
- 1st class auto-mode
- how to save modes in history (or not)?

They are all intertwined.

**Comment by Ambrevar** [comment]
If buffers had major modes, then switching from the REPL buffer to the
help buffer would automatically set the right major mode, because they
are bound to them.

It's not the only way to fix this, but major modes solve quite a few
issues along these lines (like the question of mutually-exclusive modes).
