### ISSUE TITLE
any genius here figured out how to compile this to windows

### ISSUE THREAD

**Issue by soyDESKTOP68A2MRFT** [atlas-engineer/nyxt#2005]
yeah i mean why you simply don't do it or can i do it by my own and if i can how?

**Comment by soyDESKTOP68A2MRFT** [comment]
something useful can be which are the dependencies of this

**Comment by aartaka** [comment]
@soyDESKTOP68A2MRFT, it should be possible, we are not using anything strictly *nix-specifik, afaik.

Our dependencies are listed in [docs/README.org, under the GTK depdendencies heading](https://github.com/atlas-engineer/nyxt/blob/master/documents/README.org#gtk-dependencies).

The most critical ones are WebKitGTK and, consequently, all of GTK. The FFI libraries (like `cl-cffi-gtk` and `cl-webkit`) that we rely on depend on those. Thus, you should have these C shared libraries for GTK (all of them -- including Cairo, Glib, Glib-networking, Gdk etc.) and WebKitGTK available to the compiler. If you manage to compile `cl-webkit`, then the rest of Nyxt would compile just fine, as our other dependencies are all Lisp libraries portable across systems.

We haven't yet ported Nyxt to Windows, as there are no team members that are versed in Windows way of doing things. I am the only Nyxt developer with a dual-boot Linux/Windows machine, and I don't dedicate enough time to learning Windows-based development (and Windows itself).

There is an issue about Windows compilation: #56, you can post on your attempts there. Otherwise, this issue seems to be a duplicate one :)

**Comment by aartaka** [comment]
Closing this as a duplicate. Refer to #1434 and #56 for the earlier (and more complete) discussion.
