### ISSUE TITLE
Add button to "go to source" (and install source code)

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2065]
This is easy to implement but hard to distribute, because we need to make sure that the sources are installed along Nyxt, and that Nyxt can find them afterwards in their new location!

Also we can "go to source" for non-Nyxt code if found.

**Comment by florhizome** [comment]
Since i helped tip this off...
I have been packaging a  lot of stuff with Guix the last month and I think from that i would say there is no perfect way, since distributions like Guix will continue to pop up to screw your way. other then going the extra mile in creativity ,try to provide alternatives.  
another thing that I would deem safeto say is, that you want to avoid hardcoding absolute paths yourself during build. 
Another way-to-simple thought from me is that you want to try to keep stuff together while keeping the amount of actual config files low (and to have them separated easily without having to do filtering etc)
I guess it would not be possible to (incrementally) symlink the source-path(s) into the config dir at startup, since that already means that nyxt knows where the source is? 
you can of course give an env var like EMACSLOADPATH (-> NYXTLOADPATH?) as a possible solution
