### ISSUE TITLE
Make buffers and nyxt-specific values have numeric IDs instead of strings

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2098]
Numeric IDs have some advantages over strings:
- They are strings of integers now, which doesn't make much sense. If it's a number, let it be a number :D
- `eq` is enough to compare/search. `eql` at most. It's simpler and faster. With strings, it's `equal` at least.
- Numbers are easier to encode into `nyxt:` URLs as they have no quotes.
  - May it rather be the problem of `nyxt:` URLs not being smart enough at en/decoding?
- Other browsers (conforming to WebExtensions API) use numeric IDs for tabs/windows/etc. The reasons for this are obviously beyond this issue, but there should be some. Given that conformance to WebExtensions API is quite a goal, having numeric IDs is a minor yet vital thing, given how much these IDs are passed around.

Does that make sense?

**Comment by jmercouris** [comment]
I believe you should not use a numeric type unless you are planning on doing math with it.

**Comment by shamazmazum** [comment]
Why comparing numbers with `eq` and not `=`? Seen this practice in a few places in nyxt.

**Comment by aartaka** [comment]
Then we need to use `=` in these places, ahah :)

I only used `eq` in the issue text to mark the place of integers on the scale of general equality operators (`eq`, `eql`, `equal`, `equalp`) and the corresponding complexity. I'd use `=` if it was code.

**Comment by Ambrevar** [comment]
A benefit of string ID is that they can serve to _name_ buffers, windows, etc.

Of course we could also add a `name` slot.

**Comment by K1D77A** [comment]
You could gensym keywords and then you can perform comparisons with EQ

**Comment by Ambrevar** [comment]
I thought about it again in the context of mode / buffer refactoring, and here is my current state of mind: 
- slots should be well named, well typed, unambiguous.
- let's not be too cheap on slots, they cost nothing if they are meaningful.  Better have 2 unambiguous slots than a single ambiguous one.

The initial reason why we had `id` as a string is because we conflated the concept of `name` and `id`.  However this is not obvious for a newcomer and prone to trip us as mentioned in the original post.

A good programming practice is to write _familiar_ (that is, _expected_) code.  An `id` in Lisp is expected to be a gensym (or at worst a number), but not a gensym coerced into a string.

And a buffer name is expected to be found in the `name` slot, not in the `id` slot.

Finally, we've now reached a point with Nyxt 3 where internal buffers are on par with web buffers and it makes more sense than ever to want to _name_ your buffer, but we can very well two different buffers share the same name or the ability to rename buffers (which should not change the ID).

**Comment by Ambrevar** [comment]
See #2277 for the patch.

**Comment by Ambrevar** [comment]
Fixed in #2277.

**Comment by aartaka** [comment]
Thanks, Pierre!
