### ISSUE TITLE
Update version number on master, but to what?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2144]
Many get confused when building `master` that it reports version `2.1.1-*`.

We should update it, but to what?  `2.2.4-*`?  `3-*`?

**Comment by Ambrevar** [comment]
See https://aur.archlinux.org/pkgbase/nyxt-browser-git/ for an example of confusion.

**Comment by MithicSpirit** [comment]
The issue seems to be that the 2.2.4 tag (among others) is not on the master branch. The commit for version 2.2.4 on master is de1113b8396c59589e562af64520a41e40c79acc, while the tag for 2.2.4 points to 425c71b2c124f8b3bac72d54bce184d0afd0ab1d, which is on the branch 2-series (both commits have the same changes). In subsequent releases this could probably be fixed by making the tag on master instead of 2-series. Alternatively, a slightly different tag could be used if it is desired that one exists on each branch.

**Comment by jmercouris** [comment]
what if we push the tag "master" to the `master` branch?

**Comment by jmercouris** [comment]
If you don't like this idea, I'm also in favor of `3-*`.

**Comment by MithicSpirit** [comment]
Can you please also add a tag to that commit? This would allow packagers to automate determining the version number.

**Comment by Ambrevar** [comment]
There is no version number, this is the development version.

If you want a stable release, use the 2.2.4 tag.

**Comment by MithicSpirit** [comment]
Ok. I'll just use total number of revisions for versioning then.

**Comment by MithicSpirit** [comment]
Just tested it and the issue still isn't fixed. The version is set with the `+version+` variable, which first checks the envvar `$NYXT_VERSION`, then the most recent git tag in the current branch, then lastly checks the version with asdf, as can be seen in https://github.com/atlas-engineer/nyxt/blob/57ae8bc03ce4d10c33439f23d1e7319809b6b711/source/global.lisp#L103-L110

To fix this one could just remove the second condition and jump straight to checking asdf (or add a git tag, though you seem to be against doing this on master).

**Comment by Ambrevar** [comment]
Oops!  Sorry about that.
So instead, I've opted for placing tag "3" on the first commit after
we've release 2.2.4.
