### ISSUE TITLE
Define `make-command` as `lambda-command` alias for backwards-compatibility?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2228]

**Comment by jmercouris** [comment]
I see no reason why not to do so!

**Comment by Ambrevar** [comment]
Agreed, and mark it deprecated?

**Comment by Ambrevar** [comment]
Sorry, this won't do, as I've defined `make-command` as a defun which is used to make anonymous commands functionally.

**Comment by aartaka** [comment]
Well, we can always add an `echo-warning` in the body of `make-command` :)

**Comment by Ambrevar** [comment]
But they don't have the same syntax (they can't, because `make-command` is not a macro anymore).  So we can't raise a warning because Lisp will raise an error when it encounters `(make-command foo ...)`.

**Comment by aartaka** [comment]
Yes, I just found the `make-command` definition xD Maybe rather rename it to something else and leave `make-command` as an alias for `lambda-command`?

**Comment by Ambrevar** [comment]
I went this way for consistency.  `make-*` are always functions, and the previous definitions from 2-series were not consistent.  
Since we are transitioning to a new major version, we can seize this opportunity to break backward compatibility and fix the consistency issues.

That said, if you have a better naming suggestion, I'm all ears :)

**Comment by aartaka** [comment]
Closing, as it doesn't make much sense.
