### ISSUE TITLE
Revert the documentation to the `default-configuration` examples? (and explain the customize-instance power)

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2244]
Now that #2229 is merged, our good old `define-configuration` is back—stronger than it ever was! How about we actually return all the documentation to the pre-#2194 state, with `define-configuration` as _the_ way to configure Nyxt entities?

`customize-instance` still has a place here, but it's much less featurefull than `define-configuration` and should only be advised for those favoring the OO-style of configuration.

**Comment by Ambrevar** [comment]
I disagree that it's less featureful: it's the opposite, it allows for more than just configuring slots!
`define-configuration` is arguably more convenient for slot configuration.

In my opinion, both have their place and should be documented.  I suggest we document define-configuration first, since it's easier, then proceed with `customize-instance` and more sophisticated examples.

**Comment by aartaka** [comment]
Yes, this course of action makes perfect sense!
