### ISSUE TITLE
Hamburger menu button is slightly misplaced

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#2281]
The "arrow" to the right is eating a chunk of the burger :)

Can someone fix it? :)

**Comment by aadcg** [comment]
This was introduced in d7fe3b7d7.  I'm not sure where does the CSS of `button` is defined.

**Comment by Gavinok** [comment]
@Ambrevar or @aadcg Mind sharing a screenshot. I can't seem to reproduce this but I can fix it once I see is wrong.

**Comment by Ambrevar** [comment]
Could it be a difference with fonts?
![nyxt-hamburger](https://user-images.githubusercontent.com/1489143/169593326-bd41b200-06c2-4af0-891e-b157b1ec381f.png)

**Comment by Gavinok** [comment]
Ya it's probably a font issue since our double arrow and hamburger symbols are also different sizes.

Here is the code responsible for setting the CSS up for the buttons if someone who can reproduce this wants to attempt a fix.

https://github.com/atlas-engineer/nyxt/blob/a820793eee276898e5df97d8775cd43abac814ce/source/buffer.lisp#L52-L74

**Comment by aadcg** [comment]
Yup, my hamburger looks similar to @Ambrevar's.

@aartaka, we're talking black beans hamburger here! :leafy_green:

**Comment by Ambrevar** [comment]
Well, an easy fix would be to add some safety padding right of the hamburger.
