### ISSUE TITLE
Rethinking the theme libray

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2289]
I was playing around with themes today and I noticed that our default theme doesn't follow all of the recommendations related to contrast mentioned in `libraries/theme/theme.lisp`. 

I put some thought to it and  played  a bit with a nice [tool](https://reallybigshoe.co.uk/visualiser/index.html) that computes the contrasts.

Today we're here:
![2022-05-23_18:11:22](https://user-images.githubusercontent.com/45483512/169873124-4dcd5952-aa1a-4e1a-95d8-3f1d26d5bc90.png)

A suggestion:
![2022-05-23_18:10:05](https://user-images.githubusercontent.com/45483512/169873145-664adac5-ab81-444c-98dd-26eff76ef23f.png)

EDIT: Of course it'd look awful if we were to apply these colors right now, as it can be seen below. The point was to tweak the colors to meet the criteria of having overall better contrasts.

![2022-05-23_20:52:08](https://user-images.githubusercontent.com/45483512/169895549-54161147-4e64-4702-92f9-0a655a17b387.png)

![2022-05-23_20:44:18](https://user-images.githubusercontent.com/45483512/169894736-41213be6-e003-469f-94b4-2eff4703db28.png)

Reference:
[Colors with a minimum of 4.5:1 contrast ratio on both black and white](https://dev.to/finnhvman/which-colors-look-good-on-black-and-white-2pe6).

**Comment by Ambrevar** [comment]
True your suggestion has better contrast, but I find the original theme more pleasing to the eye.  Just a personal preference.

**Comment by aartaka** [comment]
Current color themes are both parts of Nyxt identity. While we certainly can change some tertiary or quaternary colors, the accend and primary colors are too important to shift them much. We've discussed it with @jmercouris when doing a theme library — Carribean Blue is a good an recogniseable accent color.

However, having proper color contrast is important, I acknowledge that. How about this: you design accessible theme(s) (you have good ideas on those, based on our nx-modus-themes chat) and we merge those in Nyxt, and list those together with the two default themes.

This way, we preserve Nyxt identity color scheme in a default theme, while still having an easy toggle for a more accessible variant.

**Comment by aadcg** [comment]
I took some time to think about this. My idea was to port the modus themes, whose palette is in the public domain, and write an external extension. In the process, I reviewed the foundations of how we think about themes so that it's general enough for any use case.

Please see the final 3 conclusion above and tell me your opinions. @jmercouris @aadcg @Ambrevar @pdelfino

**Comment by Ambrevar** [comment]
For the box style, we have a binding to toggle the box opacity, so as long as we can toggle between high contrast and low opacity, we are good.

**Comment by aartaka** [comment]
> The WCAG guidelines help us to quantify contrast. They define the following ratios as desirable:
> 
> * 7:1 (better); easy to find colors that contrast with either `background-color` or `text-color`.
> * 4.5:1 (good); still possible to find colors that contrast with both `background-color` and `text-color`.
> 
> Is it necessary to have one color, `primary-color`, that contrasts with both `background-color` and `text-color`? Let's see where it's being used (marginal use cases omitted):
> 
> 1. html elements (h1..6, anchors, table headers)
> 2. the controls part of the status buffer (back, forward, reload, "hamburger")
> 3. hint's background (with opacity)
>
> Case 3 is the only one that _might_ require good contrast between 3 colors.

`primary-color` is the main color of interface elements. Given this purpose, it's preferable for it to have contrast with both `text-color` and `background-color`, because intrface elements tend to mix with both. Even if we don't have much cases where it happens, we should aim to preserve maximum possible contrast there.

> * [ ]  `accent-color` can't have a 4.5:1 contrast ratio with _every_ theme color. Edit its definition.

Yes! It is indeed confusing :D We should rather say that is should _stand out_, without specifying in which way!

> * [ ]  `primary-color` should have good contrast with `text-color` or, optionally, with both `text-color` and `background-color`.

I'd say the other way around! Currently, we have a lot of interface elements (buttons, table headers, prompt selection) that have 
``` lisp
:background-color theme:primary 
:color theme:background
``` 
to look integrated with both the backgroudn and the text. Because of that, contrast of `primary-color` with `background-color` is more important than with the `text-color`—it simply is a more widespread and sensible interface element palette!

> * [ ]  I really think that the `box-style` of the hints should have full opacity, otherwise we have an awful contrast and it's not the best default.

I concur with what @Ambrevar said—it's just a matter of finding a good set of colors for hints!

**Comment by aadcg** [comment]
I'm going to reply but it's important to understand that I've now read the [material design guidelines](https://material.io/design/material-theming/implementing-your-theme.html) that @aartaka got inspiration from.

Regarding the `box-style` of the hints, are you saying that we should keep the opacity and choose another color?

> primary-color is the main color of interface elements. Given this purpose, it's preferable for it to have contrast with both text-color and background-color, because intrface elements tend to mix with both. Even if we don't have much cases where it happens, we should aim to preserve maximum possible contrast there.

Not quite. `primary-color` is certainly not a neutral color, i.e. it must stand out, and it should communicate our branding (in our case it's the Caribbean blue). Regarding contrast, a foreground color must be choose when `primary-color` is in the background (the so-called `on-primary` concept in the material themes). In our case, that would be black. We're violating that principle today.

>Yes! It is indeed confusing :D We should rather say that is should stand out, without specifying in which way!

We agree. Both `primary` and `secondary` colors should stand out.

> I'd say the other way around! Currently, we have a lot of interface elements (buttons, table headers, prompt selection) that have

> :background-color theme:primary 
> :color theme:background

> to look integrated with both the backgroudn and the text. Because of that, contrast of primary-color with background-color is more important than with the text-color—it simply is a more widespread and sensible interface element palette!

Again, I'm afraid we're doing it wrong. `primary` and `secondary` colors are meant to be used on big surfaces so we don't need to care much about the contrast between `background` and `primary`/`secondary`. If you put a light grey square inside a white square, you can discern it well. What we need to take into account is the contrast ratios such as `on-primary`:`primary` or `on-secondary`:`secondary`, i.e. text or small elements that will be on the foreground.

**Comment by aadcg** [comment]
I don't think this is the right moment to make big decisions. My goal,
in the long run, is to provide a better default theme _without_ changing
the grey/blue palette.  It might not make much sense to work on #2188,
while we don't have a good foundation on the theme library.

I think I have a clear idea of how it could be done, but it requires
time and experimentation.  There are more pressing things to work on
now.

The only thing we could address right now, if we reach consensus, is to
be more precise about our concepts and properties of our theme library.

It might sound radical, but please think it through.

`background` and `on-background` are what we call background and text
colors. Their contrast ratio must be high.

The `primary` is the one that stands out and conveys the
"branding" .  `on-primary` must have a
strong contrast ratio with its counterpart.

`surface` follows the same rationale as `primary`, and one
can define as many as needed.

`primary` and all `surface`s are used on surfaces, so there are no
contrast requirements relative to `background` and `on-background`.

How does it map to what we do know?
```
| now                | proposal        |
|--------------------+-----------------|
| `background-color` | `background`    |
| `text-color`       | `on-background` |
| `accent-color`     | `primary`       |
| none               | `on-primary`    |
| `primary-color`    | `surface1`      |
| none               | `on-surface1`   |
| `secondary-color`  | `surface2`      |
| none               | `on-surface2`   |
| `tertiary-color`   | `surface3`      |
| none               | `on-surface3`   |
| `quaternary-color` | `surface4`      |
| none               | `on-surface4`   |
```

**Comment by aartaka** [comment]
I've re-read the Material Design Guidelines (MDG), and I have to highlight one thing about them: they are about designing _applications_ (single-purpose, one company, an identity that stands out), not _platforms_ (OSes/DEs/shells/computing environemtns, general-purpose, provide a neutral basis for applications to stand out from). 

Nyxt is a _platform_ for both 
- web sites (branded, colorful, mostly single-purpose, essentially _applications_) 
- and our own set of applications, like Demeter. 

Thus, Material Design guidelines are not to be taken literally there—_platforms_ have a different set of design requirements than _applications_ do. Notably, _platforms_ need to be more neutral about the brand colors: 
- GNOME only using their blue for active selection and some other highligts, otherwise going with the charcoal-ish dark theme and terribly white light theme, 
- or MS Windows allowing one to configure the whole interface with the base color (dark/light) and accent color (current selection, attention-seeking elements, some other colorized interface elements),
  - LineageOS, a fork of Android, does quite the same, allowing one to choose between dark and light theme, and giving some 10+ options for accent colors.
- or, as an example from the browser world, Mozilla Firefox—even though there is a whole palette of brand colors (fiery orange, purple, light blue, canary yellow), they are only used to highlight some particular thing and direct one attention to something.

Given this set of requirements, I believe that my adjustments to Material Design are sensible enough:
- `text` color, while it should be called `on-primary` by MDG, makes more sense as a `text` color -- it just transmits more mening this way.
- `background` color is sensible too.
- `primary` color should be a neutral gray-ish one to not require too much attention from the user, as we're being a neutral _platform_ for all types of content and branding here.
- `secondary` color should be quite neutral too, as the second most used interface color.
- `tertiary` and `quaternary` colors, although terribly named, do still make sense, as our interface is both
  - more focused than what MDG anticipate in their generality, and
  - more diverse in the types of pages that we create.
  - We just need more colors in our palette there!
    - However, the term `variant` from MDG could work here. We can use `primary-variant` and `secondary-variant` as quite a semantic naming, if those are shifted from their respective originals in the theme-specific direction.
- Finally `accent`, as I've already said, has no place in the _application_-oriented MDG, but has a placy in _platform_-specific design. For general platforms, such as Nyxt, we don't have to use lots of brand colors—the mere _platform_ usage frequency makes the `accent` color recognizeable enough. If you use a browser for four hours every day, it's enough to just color a couple of elements in Carribean Blue for you to get the identity.

Again, I've taken inspiration from MDG, yes. But MDG are still to be taken with a grain of salt, given the specificity of our use-cases. And deviating from the ~Bible~ MDG is okay here, if our case requires it. And it does.

**Comment by aadcg** [comment]
Significant progress in this front was achieved. Thanks everyone, especially @aartaka.
