### ISSUE TITLE
Use accent color for reading line?

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2298]
This way reading line is more noticeable. But then, accent color is much less neutral than the primary color.

**Comment by aadcg** [comment]
From a logical point of view, we should use the primary color since we don't invert the colors of background and text where the reading line lies. So, it's a matter of taste.

Find screenshots below. Any strong opinions?

![2022-05-25_12:06:07](https://user-images.githubusercontent.com/45483512/170248618-b5cf0859-fc07-4fbc-be8a-c98c828fecfd.png)
![2022-05-25_12:07:21](https://user-images.githubusercontent.com/45483512/170248641-5624ad15-ccdf-4568-8556-3dfc85515ef3.png)

**Comment by Ambrevar** [comment]
No strong opinion here.

**Comment by aartaka** [comment]
Thanks for testing it, @aadcg! Indeed, neutral grey works better there! Closing this, as it doesn't make much sense anymore :)
