### ISSUE TITLE
An alternative to tabs in the status bar

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2335]
Are we sure that we should display tabs in the status bar? 

Arguments against:

- Our solution doesn't scale very well since the tab bars of widespread browsers are resized as the list of tabs grows.
- It's displayed in the status buffer in the middle of the active modes and the current URL, which is a bit confusing.
- Say you have two wikipedia buffers (tomatoes and potatoes), then you'll get a single tab. 

Arguably, we'd be harming our users by not providing a simple on-screen solution to change tab/buffer. So I propose a very simple solution. Add a button at the status buffer that would trigger a panel buffer displaying the buffer list. 

Notice that the most natural UI to display opened tabs/buffers is listing the items vertically, not horizontally.

Thoughts? @aartaka @jmercouris @Ambrevar @pdelfino

**Comment by Ambrevar** [comment]
See https://github.com/atlas-engineer/nyxt/issues/1736#issuecomment-1143390625 for how "tabs" could occupy much less space and be more distinguishable from the rest.

> Say you have two wikipedia buffers (tomatoes and potatoes), then you'll get a single tab.

This is by design: then clicking on them opens up a prompt asking for which of the 2 you want.

> Add a button at the status buffer that would trigger a panel buffer displaying the buffer list.

Fine with me.

**Comment by Kabouik** [comment]
I fully agree that listing buffers/tabs vertically (with a scrollbar when needed) would be optimal, while maintaining legibility of titles. 

This is what I have been customizing my browsers to before moving to Nyxt. Instead of a button, I was using an automatically collapsible tab bar showing only favicons (in gray scale, except the active tab) and expanding upon hovering favicons with the mouse or using a tab-related keybind. Toggling on and off a panel buffer with a GUI button, a keybind, or even just while holding a key, would be nice indeed. If it becomes the main buffer bar, I assume many users would want the panel buffer to be more space efficient and more interactive than it currently is though (resizable, smaller padding, dynamically refreshing when closing a buffer).

**Comment by jmercouris** [comment]
This is an interesting idea about tagging buffers for potatoes and tomatoes. These are of course very serious vegetables. We do have the panel buffer now, but you are right, it is too rigid! It needs to be changable in size and dynamically refreshing. The panel buffer mode should probably hook into buffer creation/deletion events to update itself!

**Comment by aadcg** [comment]
We have a tab bar by default and we're committed to it.

Buffers are vertically displayed in others interfaces.
