### ISSUE TITLE
auto-mode maybe broken?

### ISSUE THREAD

**Issue by r3k2** [atlas-engineer/nyxt#2350]
Nyxt Version 3-1197-g600761a3
OS: Arch GNU/Linux
---
I'm following [this article](https://nyxt.atlas.engineer/article/auto-mode.org) to turn on by default no-script-mode and then only enable javascript on sites I trust using auto-mode.
to enable auto-mode seems to work, but when I for example ask it to enable or disable a mode, it will not save to this file:
```
~/.local/share/nyxt/auto-mode-rules.lisp
```
Just in case nyxt 3.x uses a new path I have search for it with no success.

**Comment by hendursaga** [comment]
@r3k2 what do you do, specifically? Did you explicitly run `save-non-default-modes-for-future-visits`? Or set `prompt-on-mode-toggle` to `t`?

**Comment by Ambrevar** [comment]
File persistence has recently been broken for auto-mode, it's now fixed with fb7645aeaa2682d7024a5ba52be05df8df707c36.

Does this fix your issue?

About the warnings: I'll work on it, but if you run `master` it should now report which prompt buffer it was trying to invoke.  Please report the warning and I'll fix it.

**Comment by r3k2** [comment]
yes is working now, is saving the settings. Thank you. <3   about the warnings, I  check and open a new issue.
