### ISSUE TITLE
Add a generic list-of type specifier

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2415]
Here's what I came up with, given that body of the `deftype` is actually a regular macro body with all the local functions and other niceties of Lisp:
``` lisp
(deftype list-of (type &optional (max 1000))
  (labels ((recur (depth type)
             (if (= depth 0)
                 t
                 `(or null (cons ,type ,(recur (1- depth) type))))))
    (recur max type)))
```

It allows for:
- Arbitrarily big (1000 elements are looooong lists!) lists with every element being type-checked.
- Nested type specifiers (for example, `(typep '(1 2 ("hello") nil) '(list-of (maybe integer (list-of string))))` returns `T`).
- Maximum length boundary via second (`max`) argument.

This would allow us to remove all of our quirky `list-of-*` type specifiers in favor of something to write once, use everywhere ™️.

@Ambrevar, sounds good? Any idea for improvement? I'll send a patch, but I want to improve it a little bit more :D

**Comment by Ambrevar** [comment]
Ha!  It's a funny hack, however I wonder if the Lisp reader/compiler is going to like these massive types... :)

That `max` is a bit troublesome because one of the perks of lists is precisely that they are not bounded in length.


Hmmm... If we are going to use bounded sequences, why not use vectors or something similar?


Another suggestion: have `list-of` expand to a macro like the current one, but generate the predicate from the argument (in a dedicated package to avoid pollution).

**Comment by Ambrevar** [comment]
I've done it here: https://github.com/atlas-engineer/nkeymaps/pull/2 (look at the `types.lisp` file).

**Comment by Ambrevar** [comment]
Thanks a lot!
