### ISSUE TITLE
incognito mode

### ISSUE THREAD

**Issue by easbarbosa** [atlas-engineer/nyxt#247]
Hi,

May be it still too early to an incognito mode to arrive, but at last I will make it known! 

Thanks!

**Comment by jmercouris** [comment]
It is not too early, you could implement it quite easily at the moment. Maybe a fun exercise to do ;)?

**Comment by Ambrevar** [comment]
I've pushed a fix on master which allows a workaround.  Export XDG_DATA_HOME to something temporary to create a folder for cookies, history, bookmarks, sessions, etc.

Example:

```sh
$ XDG_DATA_HOME=/tmp next
```
If your temp folder gets reset when the machine starts, then you can leave it there.  Otherwise erase all tracks with
```
rm -rf /tmp/next
```

**Comment by Ambrevar** [comment]
Of course a proper incognito mode would be nicer.

A see a couple of approaches:

- Incognito process: With an `--incognito` flag, disable history, bookmarks, sessions, etc.
Maybe it's as easy as setting XDG_DATA_HOME to /dev/null.  This is the least flexible approach.

- Incognito buffer mode: The history is not saved, the cookies are not persisted, the session won't remember this buffer.  The bookmarks are still accessible though.  This is more flexible as it does not force the user to user 2 difference processes.

With the second approach, we could still start a process with an `--incognito` flag that would force-enable the buffer mode.  But maybe that's too fragile and we should implement both approaches anyways.

**Comment by Ambrevar** [comment]
And... another enhancement on master: we now have data profiles.

Starting with `next --data-profile private` will disable all file persistence.

Next step: allow reading the history, bookmarks, etc. without persisting them.  Can this be done with a data profile?

**Comment by jmercouris** [comment]
The first thing that comes to mind is redefining the store sexp functions to be no ops, that may suffice

**Comment by Ambrevar** [comment]
Yes but how do we make a "profile" to set this?

**Comment by jmercouris** [comment]
rebind symbols to point to noop functions?

**Comment by Ambrevar** [comment]
We can just bind them to nil, no problem.

My question was about the user interface.

Do we implement it this kind of "profiles" as modes?
How do we drive them from the command line?
How do we customize them?
How do they relate to data profiles?

**Comment by jmercouris** [comment]
Ah, I see, yes that is a much bigger question than I thought.

**Comment by Ambrevar** [comment]
About the name:

- Chrome uses "incognito".
- Firefox uses "private".
- WebKit uses "ephemeral".

I think we should avoid using the first 2, because they led users to believe they are browsing the web anonymously, which they aren't.
"Ephemeral" is better but maybe a bit too technical.
Any better idea?

**Comment by Ambrevar** [comment]
@aartaka :)

**Comment by aartaka** [comment]
"Veiled" maybe? It's simple, has a material association to it and, at the same time, doesn't trick you into thinking that it's bullet-tracker-fingerprint-proof. Veil can always be lifted, after all.

It sounds quite far from privacy discource, but it's a good metafor, or at least it sounds this way for me :)

**Comment by Ambrevar** [comment]
Actually "veiled" does not speak much to me.  I suspect at least some
other users would be puzzled as to what this mode would do :p

Also "veil" may convey the false impression that this makes you
_somewhat_ incognito, while this is not the case.  The purpose of the
mode is to disable data persistence on the machine.

What about:

- spotless-mode (not sure this is very self-explanatory either)
- dataless-mode
- nodata-mode

I want to avoid "trackless" or "notrack" because that would be
misleading as well.

"ephemeral" might be good enough after all.

**Comment by jmercouris** [comment]
How about no-save-mode?

**Comment by Ambrevar** [comment]
Fine by me, although out of consistency with other "no*" modes I'd remove the
"-", so "nosave-mode".

**Comment by aartaka** [comment]
Okay, it seems that to implement this mode we need to do one of these changes (sorted from easiest to hardes) to `cl-webkit`:
- Add the `"is-ephemeral"` property to the `WebKitWebView` class.
- Add the binding for the `webkit_web_context_new_ephemeral` function and call it on `WebKitWebView`s initialization. That's easy, but it goes against the idea of having `make-instance` instead of constructors.
- Add the `WebKitWebsiteDataManager` class with at least one property -- `"is-ephemeral"`, and add the `"website-data-manager"` property to the `WebKitWebView` class.

I have done at least the first two of these and can make a PR to cl-webkit, but I'm unable to test it because of `WebKit encountered internal error` happening all the time when I'm trying to run the demo functions, even in the clean upstream version.

Another kind of difficulty is that `"is-ephemeral"` properties were introduced in the version 2.18 of WebKit, while the current version of WebKit that cl-webkit relies on is 2.4, from what I was able to infer. Too far to be easily reachable, maybe?

**Comment by jmercouris** [comment]
> Okay, it seems that to implement this mode we need to do one of these changes (sorted from easiest to hardest) to `cl-webkit`:
> 
> * Add the `"is-ephemeral"` property to the `WebKitWebView` class.

Yes, definitely possible.

> * Add the binding for the `webkit_web_context_new_ephemeral` function and call it on `WebKitWebView`s initialization. That's easy, but it goes against the idea of having `make-instance` instead of constructors.

Is it possible to create a class in cl-webkit that utilizes webkit_web_context_new_ephemeral? This way we could `make-instance` said class without issue. 

> * Add the `WebKitWebsiteDataManager` class with at least one property -- `"is-ephemeral"`, and add the `"website-data-manager"` property to the `WebKitWebView` class.
> 
> I have done at least the first two of these and can make a PR to cl-webkit, but I'm unable to test it because of `WebKit encountered internal error` happening all the time when I'm trying to run the demo functions, even in the clean upstream version.

Is it maybe because of some interaction between the `is-ephemeral` property and the constructor? Does the error happen without fail, or just frequently? Did you perchance see the other open issue about internal webkit errors and how to turn on "G Errors"?

> Another kind of difficulty is that `"is-ephemeral"` properties were introduced in the version 2.18 of WebKit, while the current version of WebKit that cl-webkit relies on is 2.4, from what I was able to infer. Too far to be easily reachable, maybe?

I don't understand the problem. 2.4 is > 2.18, so it should be OK, no?

**Comment by jmercouris** [comment]
This is the reference I have to `internal webkit errors` https://github.com/atlas-engineer/nyxt/issues/816

**Comment by aartaka** [comment]
> Is it possible to create a class in cl-webkit that utilizes webkit_web_context_new_ephemeral? This way we could `make-instance` said class without issue.

Haven't looked into it yet, but, I guess we can create anything on lisp side, but then it'll gets tricky on the C side.

> I don't understand the problem. 2.4 is > 2.18, so it should be OK, no?

No, it doesn't work this way, sadly. It's 2.18 (two-eighteen), not 2.1.8 (two-one-eight), so it was after the 2.4, I guess. Looking at the source tree: 2.4 was released 6 years ago, while 2.18 was released 3 years ago.

**Comment by aartaka** [comment]
Sorry, it's actually 2.16 that this property was introduced in. Nevertheless, it's a huge gap.

**Comment by Ambrevar** [comment]
cl-webkit does not depend on 2.4, it actually supports 2.24 minimum.

**Comment by aartaka** [comment]
Oh, I guess I was deceived by old issues :) Good to hear that, though!

**Comment by Ambrevar** [comment]
> - Add the binding for the `webkit_web_context_new_ephemeral` function and call it on `WebKitWebView`s initialization. That's easy, but it goes against the idea of having `make-instance` instead of constructors.

It's OK, actually most classes in cl-webkit are not instantiated with make-instance.

> - Add the `WebKitWebsiteDataManager` class with at least one property -- `"is-ephemeral"`, and add the `"website-data-manager"` property to the `WebKitWebView` class.

Why?  You can test this directly without a data manager by check the
GObject property or with the
https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#webkit-web-view-is-ephemeral method.

> I have done at least the first two of these and can make a PR to cl-webkit, but I'm unable to test it because of `WebKit encountered internal error` happening all the time when I'm trying to run the demo functions, even in the clean upstream version.

Weird.  Can you provide a precise recipe?  Also, do you have
glib-networking installed?

**Comment by aartaka** [comment]
> Why? You can test this directly without a data manager by check the GObject property or with the https://webkitgtk.org/reference/webkit2gtk/stable/WebKitWebView.html#webkit-web-view-is-ephemeral method.

Yes, you're right. I suggested this addition just in case the previous two won't work or we'll need `WebKitDataManager` for something. Being closer to the last API versions may be useful, after all :)

> Weird. Can you provide a precise recipe? Also, do you have glib-networking installed?

Unfortunately, I can't provide the full recipe -- it happens no matter what, both with and without glib-networking, internet connection, phase of the moon, etc. I guess this error message is too general to be the marker of the same problem in every case.

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> Yes, you're right. I suggested this addition just in case the previous two won't work or we'll need `WebKitDataManager` for something. Being closer to the last API versions may be useful, after all :)

Yes, it will be useful to have the data manager at some point.

> Unfortunately, I can't provide the full recipe -- it happens no matter what, both with and without glib-networking, internet connection, phase of the moon, etc. I guess this error message is too general to be the marker of the same problem in every case.

Are you saying it happens all the time, so you can't display any page?
But Nyxt works, right?  You must be doing something different.  Are you
using Guix somewhere?
Let me know how you test it.

**Comment by Ambrevar** [comment]
@aartaka While working on this, we need to look at #837 which would probably require the same implementation technique.  My guess is that we can hit two birds with one stone.

**Comment by Ambrevar** [comment]
If we can't make a mode (because it cannot be disabled), then the user needs another way to know if the current buffer is ephemeral or not (same with #837 by the way).  I suggest the following:

- Add a `describe-buffer` command that's just like `describe-class` but print the _values_ of the current buffer.
- Update the status formatter to print something extra when the buffer is ephemeral.

**Comment by aartaka** [comment]
I'll look into that.

**Comment by aartaka** [comment]
Okay, I won't be able to work on ephemeral-mode starting from the next week and until August because of the other workload. If you're okay with waiting until August, you can leave this task to me. Otherwise -- you're welcome to implement it earlier!

And sorry about this -- you know, things take more time than you plan them to :)

I'll finish other things that I assigned to, but ephemeral-mode is too big for the remaining time.

**Comment by Ambrevar** [comment]
No worries about that, we don't have a dead line here! :)
All community contributions are welcome at any time :)

I'm taking a small break as well, so that's perfect!

**Comment by aartaka** [comment]
Should we disable storing anything to `standard-output-path` (standard-out.txt) and `error-output-path` (standard-error.txt) in the `no-data`/`ephemeral` buffers? It sounds fair to store nothing at all for them (it's `no-data`, after all), but then it can harm us by absence of logs and inability to diagnose anything.

I'd go with storing them anyway, because they are less probable to contain sensitive information and are Nyxt-specific.

**Comment by jmercouris** [comment]
The logs to stdout and stderr may also have sensitive data. I suggest on the err of caution, and disabling those as well. I think we have enough debug data available from non-ephemeral operation.

**Comment by aartaka** [comment]
Sure, sounds good! Thanks :)

Another confusion of mine: why are there slots like `session-restore-function`, `session-store-function`, and similar ones for history? Are these there only to make the storage/restoration customizable/no-op in some cases? Is there something else to it?

I ask it this way because I want to remove these as unnecessary. They are almost unused in the current codebase. If there are no reasons except for customization of these in the `ephemeral`/`nodata` buffers, then I will be happy to remove these slots.

**Comment by jmercouris** [comment]
I am not sure about those slots, Pierre added them. Typically slots pointing to functions were added for the ease of customization. Are they needed anymore? I'm not sure. Without these can we still alter the behavior they were intended to change?

**Comment by aartaka** [comment]
These function-storing slots were not changing any behavior so far (except for the session deletion in `quit-after-clearing-session`, but it's not critical). The only solid application I can see for them is storing nothing in case of `ephemeral` buffers.

I have alternative for that in moving all the `*-data-path` slots of `browser` to `data-profile` and `data-profile` itself to `buffer`. This makes for easy per-buffer storage settings that are easier to customize. This `data-profile` movement is basically most of what I see in this changeset, except for the `ephemeral` `web-view` from WebKitGTK. After all, `data-profile` is about settings for data storage :)

What do you think of it?

**Comment by Ambrevar** [comment]
I disagree with the hash-table approach because we would lose
composition here.

Another downside of the hash-table is that it does not allow to define
the path programmatically and dynamically (at run-time).

Maybe some use cases will help clarify what I mean:

- A third-party extension adds the `foo` data-profile.  Another
  third-party extension adds the `bar` data-path.  What happens to `bar`
  (by default) when the user loads the `foo` data-profile?

- With methods, you can derive a new name on each call.  For instance, you
  could save each log entry or history entry with a timestamp in the
  name, while with a hash-table the timestamp would be set only once.

- More generally, composition needs to happen in both directions.
  This is particularly useful if we want to set default values for
  profiles (e.g. the default directory) or, independently, default
  values for data-path (e.g. the default name of a data-path).
  
  Let's consider the following data profiles: PROFILE-PARENT,
  PROFILE-CHILD, the latter inherits from the former.

  Then the user can add the following expand-data-path specializations:

  - ((profile data-profile) (path cookies-path)): Default value for
    cookies-path when no method specializes any profile.

  - ((profile PROFILE-PARENT) (path data-path)): Default for all
    data-path when using PROFILE-PARENT, e.g. this sets the base directory.

  - ((profile PROFILE-CHILD) (path data-path)): Default as above, when
    PROFILE-CHILD is selected.

  - ((profile PROFILE-PARENT) (path cookies-path)): Value for
    cookies-path with PROFILE-PARENT.  At this point, if there is no
    specialization on PROFILE-CHILD, this method will also be called.

  - ((profile PROFILE-CHILD) (path cookies-path)): Value for
    cookies-path with PROFILE-CHILD.  At this point, the above method is
    no longer called when PROFILE-CHILD is selected.
  
See
https://github.com/atlas-engineer/nyxt/issues/646#issuecomment-620446806
for a discussion.

About the methods on instances: you can also specialize on
classes, it works.  Should we have created a subclass for the private
data profile?  I don't know, I'd say no considering there is no slot
difference.  Do you have an argument in favour of creating a subclass?

**Comment by aartaka** [comment]
> I disagree with the hash-table approach because we would lose composition here. 

Valid point! I'll think about the alternatives then!

> About the methods on instances: you can also specialize on classes, it works. Should we have created a subclass for the private data profile? I don't know, I'd say no considering there is no slot difference. Do you have an argument in favour of creating a subclass?

One argument is that types are better at specifying behavior than global variables are, especially when there are a lot of instances. Having two types/classes is better than having two variables, because then the function that specializes on class will work for all of the instances, while the one that specializes on variable would work only on the ones that _are_ this variable. This doesn't scale well to the situation of multiple per-buffer profiles.

It's awkward to create two classes for seemingly similar profiles, but it's still more flexible than global variables, especially given the better dispatching it gives us. And it also looks like a more tasteful OOP -- to make two subclasses for two somewhat different sets of behavior :)

**Comment by aartaka** [comment]
> What I suggest we do is convert the storage functions to data-path methods. Thoughts? 
> Note: At the moment, if you set the function storage function to nil, Nyxt won't persist / restore the data. This is the responsibility of the caller though, which is brittle. With my above suggestion of making this a method, the caller would not have to do the `nil` check.

This makes a perfect sense! Thank for hinting at that, I'm refactoring the code to use methods and it looks much cleaner now!

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> Valid point! I'll think about the alternatives then!

Do you mean there actually is a _need_ for an alternative?  Doesn't the current
implementation satisfy our needs?

> because then the function that specializes on class will work for all
> of the instances, while the one that specializes on variable would
> work only on the ones that _are_ this variable.

Yes, this is on purpose.

> This doesn't scale well to the situation of multiple per-buffer profiles.

I don't see why.  Can you give an example?

Note that while I've used a global variable and an instance
specialization for the private profile, you are free to define a new
class for the icognito mode if it required.

**Comment by Ambrevar** [comment]
I've been thinking a bit more about the -store-function and
-restore-function.
I believe moving all these functions to methods is the right thing to
do.  Should I do it on master or do you prefer to take care of it?

**Comment by aartaka** [comment]
> I've been thinking a bit more about the -store-function and -restore-function. I believe moving all these functions to methods is the right thing to do. Should I do it on master or do you prefer to take care of it?

I've done it already, but it needs more testing together with other changes. If you don't mind waiting, leave it to me :)

**Comment by aartaka** [comment]
> Do you mean there actually is a _need_ for an alternative? Doesn't the current implementation satisfy our needs?

That's a tough question, given that now my hash-table idea is really unnecessary and methods seem to work well enough. I need to experiment and think on it for some time.

One preliminary thought is that we may need to store some buffer-unique data in `data-profile`s and that can make some buffer-local `data-profile` instances non-`eql` to e.g. `+default-data-profile+`. But I can't see applications for that yet, so it can be a premature optimization :)

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> I've done it already, but it needs more testing together with other changes. If you don't mind waiting, leave it to me :)

Great!

To be more specific, what I had in mind was:

- Remove the -store-function and -restore-function slots.
- Replace the corresponding defuns by defmethods that specialize on
  a data-profile and a data-path.  These methods can be named `store`
  and `restore`.
- Provide a default method (i.e. specialize on `data-path`)?  I'm not
  sure what to put there though.  Maybe an error?

**Comment by aartaka** [comment]
> - Remove the -store-function and -restore-function slots. 

Sure :)

> - Replace the corresponding defuns by defmethods that specialize on a data-profile and a data-path. These methods can be named `store` and `restore`.

These are really generic. Could we mean something else by (re)storing? I bet we can. Though the only alternative I can come up with is `(re)store-sexp-data` which is far from being meaningful either.

I'd go with `store` and `restore` for now.

> - Provide a default method (i.e. specialize on `data-path`)? I'm not sure what to put there though. Maybe an error?

Sounds good to me!

**Comment by aartaka** [comment]
Yet another thing: private buffers should have all the data (e.g., `bookmarks-data`, `history-data`) isolated inside them and hidden even from other private buffers, while non-private buffers usually should share all the data.
- If we store things in `buffer` slots, then we'd need to sync every non-private buffer with the general data-storage. That's hard, non-obvious and error-prone.
- If we store data in the `data-profile` instances, then, again, we need to sync it somehow.
- If we store it in global instances (e.g., +default-data-profile+, +private-data-profile+) then the private buffers won't be able to isolate their data.

What I see as a solution (I'm biased here, so point me at possible incoherences in my reasoning) is storing the data (again, user-valued serializable data, like `bookmarks-data`, `history-data`, `downloads`) in `data-profile` class (`:allocate :class`) in case of default profile and in the instances (`:allocate :instance`) in case of private profile. 

That's why using classes and making private profile a separated subclass can be worthy -- it's a built-in tool to enable intuitive behavior of `data-profile`s without resorting to global variables. I want to avoid globals in cases where they are not obviously necessary. This is the case like that -- they seem to be useful, but types/classes are more powerful and useful there, while global variables for profile-management are restraining us, instead of empowering.

How does that sound to you?

**Comment by Ambrevar** [comment]
Good point!

> - If we store it in global instances (e.g., +default-data-profile+, +private-data-profile+) then the private buffers won't be able to isolate their data.

+default-data-profile+ can remain a global instance, while
`private-data-profile` can be turned into a class.

> What I see as a solution (I'm biased here, so point me at possible incoherences in my reasoning) is storing the data (again, user-valued serializable data, like `bookmarks-data`, `history-data`, `downloads`) in `data-profile` class (`:allocate :class`) in case of default profile and in the instances (`:allocate :instance`) in case of private profile. 

I think `downloads` is not one of them! :p

As I hinted above, we might not have to use `:allocate :class` if we use
a global instance for the default profile and local instances for the
private profile.

Otherwise this seems to be a good approach!

**Comment by aartaka** [comment]
> +default-data-profile+ can remain a global instance, while `private-data-profile` can be turned into a class.
> What I see as a solution (I'm biased here, so point me at possible incoherences in my reasoning) is storing the data (again, user-valued serializable data, like `bookmarks-data`, `history-data`, `downloads`) in `data-profile` class (`:allocate :class`) in case of default profile and in the instances (`:allocate :instance`) in case of private profile.
> I think `downloads` is not one of them! :p 

Why not? Isolating downloads can be useful in case of private buffers, to separate the contexts. If we'd also change the directory where to store downloads, for every private buffer (e.g, "/home/Downloads/nyxt-downloads-%BUFFER-ID/"), this will show the data separation and help one do distinguish the downloads from each other. 

The question is: do we want to allow users to download anything in private buffers? Other browsers don't really care and allow downloads even in private tabs.

> As I hinted above, we might not have to use `:allocate :class` if we use a global instance for the default profile and local instances for the private profile.

I'm still in doubt about variable for default profile. If I'm not mistaken, modifying the value of buffer-local data-profile that was initialized with the value of `+default-data-profile+` modifies the value of `+default-data-profile+` itself. It's cool and it's something we'd expect, but `+default-data-profile+` is a hidden part of the puzzle here. Of course, it's shown to user in the manual, but this implicit pass-by-reference mutations of global variable doesn't seem obvious to me.

Storing things in classes (and, especially `default-data-profile` class) is not an obvious thing either, but it at least avoid introducing any additional references -- you really are storing things inside your buffer-local `data-profile`, it just happens to propagate it's value to all the other `default-data-profile` instances in case it is one.

It's also somewhat inconsistent to have default profile as a variable and private one as a class. `find-data-profile` (and undelying `package-data-profiles`) implies that we're consistent with profiles' representation. I can rewrite it to use classes or leave it as it is in the case of variables, but it seems hard (and not particularly elegant :) ) to implement such searching if we're inconsistent with how we represent profiles.

**Comment by Ambrevar** [comment]
Artyom Bologov <notifications@github.com> writes:

> Why not? Isolating downloads can be useful in case of private buffers, to separate the contexts. If we'd also change the directory where to store downloads, for every private buffer (e.g, "/home/Downloads/nyxt-downloads-%BUFFER-ID/"), this will show the data separation and help one do distinguish the downloads from each other. 
>
> The question is: do we want to allow users to download anything in private buffers? Other browsers don't really care and allow downloads even in private tabs.

Good question.  You are right that the private download data (the list)
should be kept separate.  But our *Downloads* buffer does not support
that yet.  It would not be very hard to fix though.

> I'm still in doubt about variable for default profile. If I'm not mistaken, modifying the value of buffer-local data-profile that was initialized with the value of `+default-data-profile+` modifies the value of `+default-data-profile+` itself. It's cool and it's something we'd expect, but `+default-data-profile+` is a hidden part of the puzzle here. Of course, it's shown to user in the manual, but this implicit pass-by-reference mutations of global variable doesn't seem obvious to me.
>
> Storing things in classes (and, especially `default-data-profile`
> class) is not an obvious thing either, but it at least avoid
> introducing any additional references -- you really are storing things
> inside your buffer-local `data-profile`, it just happens to propagate
> it's value to all the other `default-data-profile` instances in case
> it is one.

I find it more explicit to use a global variable to share state than a
class with `:allocate :class`.  The latter is a relatively rare
behaviour that's not obvious.

You talked about "this implicit pass-by-reference mutations of global
variable" but isn't it explicit actually?

> It's also somewhat inconsistent to have default profile as a variable and private one as a class. `find-data-profile` (and undelying `package-data-profiles`) implies that we're consistent with profiles' representation. I can rewrite it to use classes or leave it as it is in the case of variables, but it seems hard (and not particularly elegant :) ) to implement such searching if we're inconsistent with how we represent profiles.

Indeed, we might need to ensure more consistency here.

**Comment by aartaka** [comment]
> I find it more explicit to use a global variable to share state than a class with `:allocate :class`. The latter is a relatively rare behaviour that's not obvious. 

Fair point, it's quite rare. Though I haven't seen MOP being used as expansively anywhere, as it is used in Nyxt code -- it's quite rare too :)

> You talked about "this implicit pass-by-reference mutations of global variable" but isn't it explicit actually?

It was explicit in case of global profiles that were unique for browser. It's only one value that you modify when you modify explicitly global `(slot-value *browser* 'data-profile)`, after all. 

When we move `data-profile` to buffers, global variable and global slot becomes a kind of shared resource and the modifications of _buffer-local_ profiles' values modify the global value implicitly. It's less clear and there appear more layers of indirection, while, if we use class-allocated slots, it's one less layer at the cost of rare CLOS feature being used. Given that MOP is not always obvious yet it is used in Nyxt, I think that class-allocated slots are a good way to go!

**Comment by Ambrevar** [comment]
> It's less clear and there appear more layers of indirection, while, if
> we use class-allocated slots, it's one less layer at the cost of rare
> CLOS feature being used.

In my understanding, it's only moving the layer of indirection.

Anyways, no strong opinion on this, both approaches seem to work, feel
free to go with the one you prefer! :)
