### ISSUE TITLE
Duplicate Hints

### ISSUE THREAD

**Issue by hendursaga** [atlas-engineer/nyxt#2516]
**Describe the bug**

When I run something like `download-hint-url`, an `<img>` tag enclosed within an `<a>` tag (and presumably other combos) downloads the exact same URL twice. This makes sense since the selector for `download-hint-url` is `"a, img"`.

**Precise recipe to reproduce the issue**

1. Visit https://google.com/
2. Run `download-hint-url` and select the Google Easter egg.
3. Run `list-downloads` and see for yourself.

Alternatively, visit some 'booru and try downloading any of the images there.

**Comment by aadcg** [comment]
It should be mentioned that if an image is not encircled by an `a` tag, then df86d95 won't fix it. Correct @aartaka?

**Comment by aadcg** [comment]
It's ok to keep it as is! The important thing is to leave this note to remind ourselves.

**Comment by hendursaga** [comment]
I actually was thinking more along the lines of deduplicating URLs when at least downloading, as I generally do a lot of downloading images and videos..

**Comment by aartaka** [comment]
Huh, then it qualifies for a feature, I guess :sweat_smile:

**Comment by aadcg** [comment]
We'd have to compare the `href` attribute of `a` emements against the `src` attribute of `img` elements.

But, in my view, a more meaningful way of going about it would be to enter "image" in the prompt buffer right away, since those are the types you want to download. Then it's possible to mark the desired images by adding the corresponding hint strings.

Well, regardless, this would hold if we'd revert the selectors to `"a, img"`, which I guess is open to debate...

**Comment by aadcg** [comment]
> We'd have to compare the `href` attribute of `a` emements against the `src` attribute of `img` elements.

Well, or do something way better as @aartaka did in 6196f12!

**Comment by aartaka** [comment]
xD

**Comment by aadcg** [comment]
This is a tricky topic. @aartaka noted that there may be several buttons with the same URL that are used for different
side-effects.

I'll keep this issue closed, as it's not clear in which cases we could even theoretically remove duplicated.
