### ISSUE TITLE
Naughty download path

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2648]
### The Download Page has a dropdown
- "Download for GNU/Linux"
- that dropdown has an option for Ubuntu x86-64 which is not functional.

![Screenshot 2022-11-14 at 4 21 1](https://user-images.githubusercontent.com/6666079/202524435-460ab492-500e-41bf-ba4c-42e6d713b8c8.png)

- [ ] Please temporarily remove this so that users follow the "All distributions (x86-64)" path

**Comment by aartaka** [comment]
A little bit of context by @jmercouris: the newest stable Ubuntu (22.04) doesn't have a version of libssl that we rely on anymore, and somehow replacing/providing it is not feasible. @jmercouris, correct me if I'm wrong :P

**Comment by Ambrevar** [comment]
We can still support 20.04, nah?

**Comment by aadcg** [comment]
None of us uses Ubuntu, I believe. 

Should we really maintain it when we have this other possibility (`guix pack`) that works on any GNU/Linux distribution?

**Comment by Ambrevar** [comment]
20.04 works and costs nothing to keep it.

**Comment by aadcg** [comment]
I agree @Ambrevar!

I guess that perhaps we should highlight the GNU/Linux bundle since, as of today, both are equally on the spotlight.

**Comment by jmercouris** [comment]
I believe it costs something to keep it. People will try to use it on newer Ubuntu distributions, and it won't work, and then they shall be frustrated, which I think is double plus not good.

**Comment by aadcg** [comment]
My opinion may sound extreme but let me explain.

We develop Nyxt openly and all we should provide is the source code. The subject of software distribution is not the deal of software developers, at all!  This a general observation. But, in our very concrete case, since we use Guix to manage our development environment, we have an amazing mechanism to distribute Nyxt. So, in my view, our responsibility on software distribution ends there (source + the output of `guix pack`).

As Nyxt matures and people become interested, they will make it available in other platforms, package managers, etc. 

Of course that any of us, as dev team members, MAY happen to be responsible for maintaining Nyxt distribution in other platforms. But that only makes sense when you REALLY use it.

I don't think any of us uses Ubuntu, so it makes little sense to sustain that burden.

**Comment by jmercouris** [comment]
Your opinion is not that extreme. The only reason we had an Ubuntu deb available was to help Ubuntu users and thus increase adoption. As it is quite easy to use the Guix pack, I don't think that is necessary anymore.

**Comment by jmercouris** [comment]
This is closed in this repository, we can continue discussion in the website repository!
