### ISSUE TITLE
define-class: Allow docstring after initform

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2688]
**Is your feature request related to a problem? Please describe.**
Our `define-class` macro already does a lot of nice shortcuts. What would be even more contenient as allowing to include the slot documentation right after the initform, so that one does not have to write lengthy `:documentation` keyword and can mirror the intuitive `defvar`-like order of slot definition.

**Describe the solution you'd like**
Allow documentation inclusion after slot initform, like:
``` lisp
(define-class foo ()
  ((slot-a
    4 "Some value"
    :export nil)))
```

**Describe alternatives you've considered**
Using a mere `:documentation`. Totally fine, but having something more intutive, short, and habit-forming is nicer.

**Comment by Ambrevar** [comment]
Not sure it's possible: `class*` looks at the number of slot options to know what to do:
- if it's odd, then the first value is the `:initform`.
- if it's even, then use the standard CL behaviour.

So allowing for a positional documentation breaks this logic.  In particular, how can we logically tell the options apart in case the `:initform` is a keyword?  For instance

```(lisp
(slot-a :my-value "my doc")
```

The above would be ambiguous with @aartaka's suggestion, since `:my-value` could very well be a class option (depending on the metaclass).

**Comment by jmercouris** [comment]
I agree with Pierre's assessment. I believe this to be impossible to cleanly implement.
