### ISSUE TITLE
Fix `nyxt/prompt-buffer-mode:{next,previous}-page`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2742]
Commands `nyxt/prompt-buffer-mode:next-page` and `nyxt/prompt-buffer-mode:previous-page` don't work as expected.  They don't update the list of suggestions by a full page (i.e. by all visible ones).  Also, the current suggestion should be set to the index of the current suggestion (with respect to the visible suggestions) before running the command.

The JS logic in `step-page-index` needs to be reviewed.

**Comment by aartaka** [comment]
Right, now that we make prompt buffer to occupy 1/3 of the screen, instead of the constant 256px, it's much more challenging of a logic :D

I'd say that the issue is a bit more general now: prompt-buffer has to be a bit more [responsive](https://en.wikipedia.org/wiki/Responsive_web_design) in it's HTML/CSS!
