### ISSUE TITLE
qutebrowser style hinting

### ISSUE THREAD

**Issue by port19x** [atlas-engineer/nyxt#2768]
**Is your feature request related to a problem? Please describe.**

I'm just now checking out nyxt after many months on qutebrowser.
Your hinting seems weird and provides a worse user experience to me.
During hinting on nyxt I have to use more keystrokes while seeing less on the screen.

**Describe the solution you'd like**
(please inform me if you already support one or more of the following)

- option to disable text-hinting (only have the letter combinations)
- option to have incremental hinting (#2509)
- option to hide prompt-buffer
- option to automatically follow hint once only one match remains (saves `RET` keystroke)
- option to limit hinting characters (e.g. to the home row)
- some wrapper option documented somewhere for migrating users

**Describe alternatives you've considered**
Some of this could, and probably should, be default.

**Side by side comparison**

Each browser occupies 1/4 of the screen here.
Testing site: [geizhals.de](https://geizhals.de/) (price checking website)

Nyxt
![nyxt-hinting](https://user-images.githubusercontent.com/82055622/216815271-7c2c53c0-9ceb-4fbe-ae4c-17f052f7667a.png)

Qutebrowser
![qutebrowser-hinting](https://user-images.githubusercontent.com/82055622/216815304-f772a4ac-a673-4120-91a4-09eda4b363a9.png)

**Comment by aartaka** [comment]
I cannot agree with the remark about the weirdness and "wrong"ness of our hint-mode, because the way it's done now is the result of long debates on what is useful for a broad group of users, including those (like myself) that actually look at the text on the page and orient themselves based on this text, instead of link hints.

> * option to disable text-hinting (only have the letter combinations)

See the `nyxt/hint-mode:fit-to-prompt-p` slot of `nyxt/hint-mode:hint-mode` (Nyxt-internal docuementation link is `nyxt:describe-slot?class=%1Bnyxt%2Fhint-mode%3Ahint-mode&name=%1Bnyxt%2Fhint-mode%3Afit-to-prompt-p`). Example config:
``` lisp
(define-configuration nyxt/hint-mode:hint-mode
  ((nyxt/hint-mode:fit-to-prompt-p t)))
```

> * option to have incremental hinting ([Incremental tree-style hinting #2509](https://github.com/atlas-engineer/nyxt/issues/2509))

It's not yet there, but, given that there's an issue on that, we'll get to it someday :)

> * option to hide prompt-buffer

`fit-to-prompt-p` should do that too.

> * option to automatically follow hint once only one match remains (saves `RET` keystroke)

See the `nyxt/hint-mode:auto-follow-hints-p` slot of `nyxt/hint-mode:hint-mode` (Nyxt-internal docuementation link is `nyxt:describe-slot?class=%1Bnyxt%2Fhint-mode%3Ahint-mode&name=%1Bnyxt%2Fhint-mode%3Aauto-follow-hints-p`)
``` lisp
(define-configuration nyxt/hint-mode:hint-mode
  ((nyxt/hint-mode:auto-follow-hints-p t)))
```

Although it seems broken at the moment :D @aadcg, any idea why that might be?

> * option to limit hinting characters (e.g. to the home row)

See `nyxt:manual#slot-configuration` in Nyxt or re-use this code snippet for your case:
``` lisp
(define-configuration nyxt/hint-mode:hint-mode
  ((nyxt/hint-mode:hint-alphabet "asfdghjkl")))
```

> * some wrapper option documented somewhere for migrating users

Yeah, our docs are not exactly exhaustive on this topic, and the settings system is currently under reconstruction, but we're getting there :)

> **Describe alternatives you've considered**
> Some of this could, and probably should, be default.

No. Default Nyxt tries to be the least specialized setup, with no particular user group in mind. Most of our team are Emacs setup users, while lots of users and active contributors are VI people. We want to retain the neutrality of the default Nyxt as much as we can.

Given that Nyxt is also configurable enough, it's implied that your favorite setup is a matter of you choosing/hacking the setup you want based on the faceless default one. Especially given that most of your concerns actually have a toggle already implemented for them :)

**Comment by port19x** [comment]
Well, since most of these have configuration options that's fine.
Thanks for the help

**Comment by aadcg** [comment]
> Although it seems broken at the moment :D @aadcg, any idea why that might be?

I couldn't reproduce. Can you provide a recipe?

**Comment by aartaka** [comment]
> I couldn't reproduce. Can you provide a recipe?

Oh, right, was some Heisenbug, I cannot reproduce either...
