### ISSUE TITLE
`fuzzy-match` behavior when input doesn't match any suggestions

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2792]
It's reasonable to expect that a filtering mechanism returns a proper subset of suggestions when matching against input. In some cases that subset might even be the empty set.

However, `fuzzy-match` return all suggestions in some situations.

Example:

- Issue `execute-command`; 
- Run `(length (prompter:suggestions (current-source)))`; 
- Set the input to something bogus, say "sklfjslkfjslfjsk"; 
- Run `(length (prompter:suggestions (current-source)))`

Both calls to `(length (prompter:suggestions (current-source)))` return the same value. 

I find this behavior extremely strange. 

CC @lansingthomas @jmercouris @Ambrevar @aartaka.

**Comment by Ambrevar** [comment]
I find it matches the expectation of "fuzziness".

You can tweak this behaviour by using `delete-inexact-matches`.

**Comment by Ambrevar** [comment]
It depends how you think about it.  You are taking the logical angle, but the current implementation follows a practical "do what I mean" angle: showing nothing in the prompt buffer is useless, because there is nothing to do then.  So we'd rather display everything then so that the user can select suggestions and act upon them.

It would be clearer if we highlighted the matching parts in the suggestions.  For instance with input "foo bar", suggestion "foo17" would have `foo` highlighted.  In case of no match, suggestion "whatever" would have nothing highlighted, thus making immediately clear that the fuzzy-match didn't match anything.

What do you think?

**Comment by Ambrevar** [comment]
The missing highlight feature I'm talking about is referred to in https://github.com/atlas-engineer/nyxt/issues/1213.

**Comment by aartaka** [comment]
I had encountered this behavior more than once, and I'm not sure it's the most intuitive. I myself would rather have an empty prompt than the full one with confusingly irrelevant matches.

**Comment by aadcg** [comment]
@Ambrevar I've  now fully understood your perspective. 

The point where I'm afraid we disagree is when you mention:

> (...) showing nothing in the prompt buffer is useless, because there is nothing to do then.

I believe that empty suggestions would communicate: "there's a typo in your input" or "the thing you're looking for doesn't exist".

I believe this is in line with @aartaka's last comment.

**Comment by Ambrevar** [comment]
Yup, but if we had match highlighting, then we would also convey this information, since the first match would not have the input highlighted.

This is how Helm works.

**Comment by aadcg** [comment]
I agree that it would help convey the information, but I think that match highlighting is desirable regardless of the conclusion on the topic at hand. In short, I believe that even if we had match highlighting right now, it's still worth discussing this topic. 

We can come back to this at a later time with @lansingthomas and @jmercouris.

**Comment by Ambrevar** [comment]
In any case, I don't have a strong opinion about this.  If you all think it'd be better to hide non-matching results, no problem.

**Comment by lansingthomas** [comment]
You dudes already know this but I will say it anyway. 

If a system returns an empty value -- there should be a rendered indication. It is important because it helps users problem solve. A clear status indicator anywhere (message buffer or wherever) lets the user know that the input was appropriate, even though the search returns nothing useful.

we could have something fun when this happens 
- _even our powerful fuzzy search has nothing for "sklfjslkfjslfjsk"_

Or something simple that still communicates that the system is working
- _no result_

Maybe someone can explain match highlighting and the rest of this context on our next call.
