### ISSUE TITLE
Augment the key binding facility (advanced VI features)

### ISSUE THREAD

**Issue by averrin** [atlas-engineer/nyxt#28]
I am emacs user, but big fun of vim-like bindings. So i use cVim and already cannot use other keys=(

I think something like spacemacs will be very popular

**Comment by jmercouris** [comment]
Hi, thank you for your interest!

I am sorry to disappoint, but Evil mode is not planned, though something akin to hydra is planned, if you'd like to see evil mode incorporated, I am happy to accept any PR or suggestion on how to maybe incorporate Evil mode, we could put it in the timeline, and if it gets enough traction maybe we can even complete it :P

**Comment by LaloHao** [comment]
A good starting point would be defining what evil-mode is in the browser.

So far i'd think of `jk` instead of `C-p` and `C-n`
Remapping `C-g` to `/` maybe?
`ESC` to exit minibuffer

Perhaps we could work out something together

**Comment by jgkamat** [comment]
I don't think mapping j/k is feasable unless there's a mode system, as you won't be able to type j/k into web pages unless you switch modes. You could try `C-j` or `C-k` though. This could work out fine though if you just use an external editor to edit text fields.

**Comment by averrin** [comment]
I need not vim in text fields, but i need j/k navigation and other one-letter shortcuts. Evil is about modes not text editing.

**Comment by jmercouris** [comment]
one needs modes to distinguish “j” from typing in a “j” into a text field. to answer the question, nEXT does support modes, therefore one could program an evil emulation thing

**Comment by HiPhish** [comment]
If I may chime in, I think one should distinguish between vi-keys for the browser interface and vi-keys for typing in text fields. vi-keys for the browser could be implement as simple mappings for the most part, but text fields are a different beast.

Rather than emulating a complex system I think it would be easier to integrate nEXT with Neovim. A headless Neovim process could be started (maybe lazily only after the user as actually entered a text input) and then the text field would serve as a a GUI for the headless Neovim. This would effectively give users their whole Neovim setup with all their customizations for entering text rather than just an approximation. I for instance rely a lot on key bindings because the default vi bindings don't make sense on a non-English keyboard.

I don't expect this sort of thing to be part of nEXT though, it should be a plugin instead.

There is something else I wonder: what if a web page introduces its own key bindings? Like, if it does something when the user presses `j`, does the page get the key before nEXT gets it? After? Does the key press get consumed or would both the web page react and the page get scrolled?

**Comment by braham-snyder** [comment]
@HiPhish https://github.com/ardagnir/pterosaur

**Comment by pseudonamed** [comment]
As an Emacs and Evil user I'd be super happy with a Lisp configured Vim-ish browser so I do hope there is some traction behind this.

For anyone wanting something right now there is [Qutebrowser](https://qutebrowser.org/) which is a Vim-ish browser heavily inspired by dwb which scratches that itch. It's just configured in Python rather than a Lisp.

**Comment by lehmacdj** [comment]
[Here](https://gist.github.com/lehmacdj/b3c897ab46af34574b2947f8dc4e937d) is a little implementation of some evil-mode mappings. Currently we are waiting on #58 for this to work, but I already implemented a fix in #62.

I haven't implemented an insert mode yet, so it can cause some problems typing in text fields sometimes (probably the right thing to do is to detect if we are in a text field and disable mappings if that is the case instead of requiring switching to insert mode in the long run, of course an insert mode will still be needed for pages that require the bound keys).

Additionally the implementation is far from perfect, the way I manage to make evil the initial mode, is by overwriting the function 'document-mode that is called to create the initial mode!

We need some better support for modes, including probably setting an initial mode in order to make evil in nEXT a reality, but for now this does a pretty good job for most things now.

I modeled most of the keybindings off of the [cVim keybindings](https://github.com/1995eaton/chromium-vim).

**Comment by lehmacdj** [comment]
I added an insert mode which can be entered using `i` and exited using `ESC` or `C-[`.

**Comment by Ambrevar** [comment]
Hey all!

I'm going to work on this for the next few days.
There are a lot of good ideas in this thread, so I'll consider all that.

I'm wondering if any Evil gurus would have suggestions before we get down to work.
@TheBB, @wasamasa, @jojojames, @justbur, @noctuid, @jgkamat?

It's not just about Evil/VI keybindings, but also about more general concepts
such as key translation, leader keys, etc.

Since we are starting from scratch we don't depend on Emacs' history, so let's
not make the same mistakes :)

**Comment by wasamasa** [comment]
It bears repetition that Evil is first and foremost about implementing Vim's text editing model. Most of its smarts is about implementing Vim's grammar in an elegant and extensible way. Assuming you don't plan on implementing Vim's editing model in text input fields (it's far easier to just shell out to an external editor), this leaves a few much smaller concerns to worry about:

- The flexibility of Emacs keymaps is what allows Evil to work pretty well with one notable exception, automatic resolution of conflicting key bindings with a timeout. A popular example of this is mapping something like `kj` in insert mode to exit from it. This conflicts with `k` in insert mode. Vim allows you to bind both and waits with a timeout whether `k` is followed by j`, then either exits from insert mode or inserts `k`. Emacs doesn't allow you to bind this, so far I've only seen special-purpose hacks to work around this limitation.
- The Vim grammar is the reason why Evil's key lookup is so complicated. If it's not present (like if the most complicated command that can be executed is `gg` or `ZZ`), you don't need to create a complicated state machine like in Evil.
- Repeating commands or allowing keyboard macros is another thing that can make things complicated. It's doubtful how useful it is in a browser context though. After all, in this browser you can just write some code to solve an ad-hoc task...
- Leader keys are just a special case in key look-up. They can be emulated by translating the leader key, using a leader key map or using a few lines of code to create a `define-leader-key` macro.

These issues aside you're best off studying other popular browsers and browser extensions that implement Vim-style browsing, such as dwb, vimperator, pentadactyl, qutebrowser, etc. They'll show you what features are exposed by which keys.

**Comment by noctuid** [comment]
> automatic resolution of conflicting key bindings with a timeout... Emacs doesn't allow you to bind this, so far I've only seen special-purpose hacks to work around this limitation.

Fwiw, `general-key-dispatch` is general-purpose (though the implementation is still hacky).

The various vim browser extensions I've tried support timeouts, so this is a feature worth considering. It matters less when you don't have operator/object keybindings though (since this is generally where people use this functionality besides in insert mode).

> Repeating commands or allowing keyboard macros

I think this is also worth considering. It's not a common use case at all, but I've definitely used both with pentadactyl. I'd say counts are more important than either though and probably wouldn't miss macros much.

Pentadactyl has `<leader>`. I don't think qutebrowser does, but it's configurable in python, so you could just use variables. I agree that it's not a big issue. I see no reason to do anything special for named prefix keys if the configuration is in lisp. The user could just store a key in a variable and create a wrapper keybinding function/macro. You could provide a `:prefix` keyword or something similar if you wanted to make this easier. I guess you will want to consider whether you want to support the equivalent of Emacs' prefix keymaps. I haven't seen anything like this in vim browser plugins; they generally just allow you to bind keys in different modes like insert, caret, normal, command, etc.

The only other thing I have to add is to agree that you should look at existing implementations like pentadactyl, qutebrowser, and tridactyl. Pentadactyl is one of the best pieces of software I've ever used. It has great documentation and despite being pretty much dead for years, nothing even matches it in terms of functionality. Tbh, I think this is a pretty hard thing to do; an insane amount has gone into these plugins. If you're only looking at the keybinding aspect, a lot of the functionality of these plugins isn't relevant. One thing I would put a good amount of consideration into is how to do buffer/domain-local keybindings. This was/has been a huge annoyance in qutebrowser, and there was a massive discussion going on about it for a while. Pentadactyl had a groups feature where you could create a group that matched urls with limited regexp and then create keybindings for those groups. [Here](https://github.com/tridactyl/tridactyl/issues/808#issuecomment-425757676) is a relevant tridactyl issue with a lot more information.

**Comment by Ambrevar** [comment]
Thank you all for your comments and sorry for the absurdly long delay (lots of work had to be put into more urgent things).
Initial VI binding implementation is in progress in #235.  It does not cover all the fancy features of Pentadactyl but it's a start ;)

**Comment by Ambrevar** [comment]
I've just merged the pull request! 

Let's keep this open until the remaining, more advanced features that could be expected from VI bindings are implemented:

- Repeat key (e.g. C-s s s s)
- Keyboard macros
- Numeric arguments
- Conflict resolution with timeout (e.g. j/k to escape)

**Comment by sivark** [comment]
> something akin to hydra is planned
I use Emacs Doom, so I would love a hydra like interface that can be launched with a leader key. BTW, just wanted to mention Hercules for inspiration (roughly, auto generated hydras): https://gitlab.com/jjzmajic/hercules.el/

**Comment by Ambrevar** [comment]
VI bindings are also missing from the minibuffer.
Once we have a status bar (#608) it will be easier to give user feedback about the VI state.
Then VI bindings for the minibuffer will be trivial.
Note that it should be separate from webview bindings, since some users prefer VI bindings in the webview and non-VI bindings in the minibuffer.

**Comment by edgar-vincent** [comment]
> Once we have a status bar (#608) it will be easier to give user feedback about the VI state.

Are you still planning on adding this feature? I think it would make things a lot easier for vim binding users :)

**Comment by Ambrevar** [comment]
edgar-vincent <notifications@github.com> writes:

> Are you still planning on adding this feature? I think it would make things a lot easier for vim binding users :)

We already have a status bar, so we could color the mode part in the
status differently.
Is this what you had in mind?

**Comment by edgar-vincent** [comment]
Absolutely!

**Comment by Ambrevar** [comment]
Would you be interested in contributing this feature?  It's a good one
to get started ;)

**Comment by edgar-vincent** [comment]
Very much so!  I know no Common Lisp at all, just a little Elisp (and I'm not a programmer), but I'll try :)

**Comment by Ambrevar** [comment]
Thanks!
And thank you for all the feedback you are giving us! ;)

**Comment by edgar-vincent** [comment]
Thank you for being such a kind, patient and open dev team :)

**Comment by Ambrevar** [comment]
See #1220 for `n` and `N` to search forward and backward.

**Comment by Ambrevar** [comment]
Thanks to @edgar-vindent, the VI indicator is now displaying in the status bar!

Next: disable key insertion in normal mode.

**Comment by Ambrevar** [comment]
See https://github.com/atlas-engineer/nyxt/issues/739.

**Comment by edgar-vincent** [comment]
> Thanks to @edgar-vindent, the VI indicator is now displaying in the status bar!
> 
> Next: disable key insertion in normal mode.

Thanks @Ambrevar! It would be nice if the indicator were also affected by the vi-mode enabled in the current prompt buffer.

**Comment by jmercouris** [comment]
Those are two distinct things though, we can add another specific display for that.

**Comment by Ambrevar** [comment]
I second that.

**Comment by Ambrevar** [comment]
VI indicator added to prompt buffer with 08d29ae9cf408fc2515c5f49c4af3c1a59ae9bcd.

**Comment by Ambrevar** [comment]
And vi-normal-mode no longer lets printable characters through with b73a2d28ede3dd48746325348215f89bdb2e5b58.

**Comment by aadcg** [comment]
Done.
