### ISSUE TITLE
Re-enable global history

### ISSUE THREAD

**Issue by aartaka** [atlas-engineer/nyxt#2862]
Setting `global-history-p` to NIL by default cuts off one of the (subjectively) most useful and novel Nyxt features—history globality. Given that this change was smuggled through in #2708 [without any announcement](https://github.com/atlas-engineer/nyxt/compare/15e3ad0c78c86710f6347d4fdd8faa4afefc2d65..b929361ba0b342da75ec56aa89e6cce919b14e10), there wasn't much discussion (except for a private call between @aadcg and @jmercouris) about whether it's right to set it to NIL. 

#1677 cannot be used as a justification for this change: the last state of it was
- GHT is unreliable.
- But so it every new approach and code.
- Let's fix the actual bugs there are, and see how it compares to the latest, bug-free, state of per-buffer history.

Not all bugs were fixed prior to #2708 (and #2708 itself doesn't fix any either):
- #2660
- #2252
- #1117
- #1848

thus global history may not be said to be inferior and one must have a solid reason to disable it. There's none of such reasons that I've seen. Prove me (or, rather, global history) wrong @jmercouris.

**Comment by aadcg** [comment]
The word "smuggled" doesn't seem appropriate. It was a joint decision, and @jmercouris and @Ambrevar talked about it too.

Ultimately, working and bug-free concepts are the ones that are used in production. When global history reaches that status, the decision could be revised. Therefore, I consider that the decision taken was the only possible one!

Personally, I think that pursing a robust global history is not a priority as of today.

**Comment by jmercouris** [comment]
I still believe that the global history tree should not be enabled by default. Yes, at the time it was very unreliable. Today, it is perhaps more reliable, but there still exists a fundamental problem. I believe it is too complex.

For whatever reason, I cannot visualize what pressing `C-b` will do, where it will take me. If I can't visualize it, as a very advanced user, I don't think many will be able to. I was also not alone in this, if I am not mistaken, Pierre (who I consider to be an even more advanced user than myself) had great difficulty in understanding the GHT.

I believe the buffer local history tree strikes a balance between being more sophisticated than the simple list of a modern browser, while also being comprehensible for most users.

Lastly, let us please not assume the intent of others! I am specifically citing the IRC guidelines which I've found great value in applying generally.

```
We therefore recommend that you assume good faith and, in the event of a potential misunderstanding, ask for clarification rather than accuse.
```
https://libera.chat/guidelines/

I am saying this because the context of the word `smuggle` carries with it an implication of intent.

Smuggle:
```
To bring into a country (a prohibited item) secretively and intentionally, in violation of the law.
```

This is not what happened. What happened was a discussion, and then a compromised decision.

**Comment by jmercouris** [comment]
My friend, let us not forget we are on the same team :-)

**Comment by Ambrevar** [comment]
> Pierre (who I consider to be an even more advanced user than myself) had great difficulty in understanding the GHT.

To clarify, I had difficulties wrapping my head around the implementation model, but not the usage.

In find the GHT easy to use and wrap one's head around in practice.

**Comment by aartaka** [comment]
> I am saying this because the context of the word `smuggle` carries with it an implication of intent.

Indeed, "smuggle" is too emotionally charged of a word, I guess. Sorry about that, didn't realize the weight of it.

> This is not what happened. What happened was a discussion, and then a compromised decision.

As I've already said, there was no _public_ discussion about toggling GHT off. Git/GitHub history remembers it all: there was a message by @aadcg saying that @jmercouris and he are going to discuss the defaults privately. Then there was a set of rebases/force-pushes and the PR was merged. Before @aadcg's message, GHT was on. After the merge, it was off. No announcement, no commit message stating it. Nothing. That's why I was shocked to find GHT off _a month_ after it was toggled. 

I, as any outside spectator, was blissfully unaware of the change, because there was no _public_ discussion. And there should be one, so that everyone has a say. This PR is the place for this discussion.

**Comment by aartaka** [comment]
I so take it, we have it settled at re-enabling global history?

**Comment by jmercouris** [comment]
No, it would be potentially disastrous!

**Comment by aartaka** [comment]
> No, it would be potentially disastrous!

That's a sarcasm, I guess. Okay, I'll open a PR soon.

**Comment by jmercouris** [comment]
I was not being sarcastic, I don't think it is stable enough.

**Comment by aartaka** [comment]
It is. Please rebuke the arguments above instead of repeating what was already proven not-exactly-true (at least) by them.

**Comment by jmercouris** [comment]
You've made good arguments. Let's re-enable it for now. *But*, I strongly suggest we keep an eye on this! If it is problematic and unstable, let us not hesitate to disable it!

**Comment by aartaka** [comment]
OK, considered that bugs in the top post are addressed for a fair comparison. I'll send a PR re-enabling GHT soon.
