### ISSUE TITLE
Conjunction of the Spheres -- Merging (Legacy Tutorial) with (Manual)

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#2890]
Related to the ongoing efforts to update the tutorial [2676](https://github.com/atlas-engineer/nyxt/issues/2676)

As we replace `How Do I...`(panel) with the new `panel-tutorial` and update the `Tutorial` button we must update nyxt:`Manual` with the information contained in nyxt:`tutorial` This issue should be closed when that  nyxt:`tutorial` information goes to the nyxt:`Manual` page. 

Overhaul of that page is a big adjacent project for sometime soon.

**Comment by aadcg** [comment]
The idea of merging the legacy tutorial with the manual seems like a good one. 

Personally, I wouldn't call a piece of information displayed in a panel buffer a "tutorial", since a tutorial is a more in-depth piece. This new writing is a short introduction to cover the bare basics, so "quick start" or something similar seems more appropriate. 

I don't think we're losing much by abandoning the legacy tutorial since it's not a particularly good piece. Also, the new quick start will help new user in a way that we don't do today.

**Comment by lansingthomas** [comment]
update: Artyom and I are meeting on Monday to get me set up for taking some action on this issue

**Comment by aadcg** [comment]
@aadcg and @lansingthomas have been making progress on the new interactive tutorial. 

I'll close this issue once the new interactive tutorial is ready.

**Comment by aadcg** [comment]
This issue is related to #976.

**Comment by lansingthomas** [comment]
I notice that a few other GH issues have been opened addressing similar topics:
_The structure of our documentation for both early learners and seasoned users_
- #976 - removing (or not removing) redundant tutorial info
- #2676 - the quick-start panel
- #3067 - make individual elements of the documentation easier to find with cross-linking

I also notice that some ideas are floating around:
- interactive tutorial beyond the basics covered in `quick-start`
- improve the content of Manual
- improve the content of Tutorial
- improve the typography/visual communication of all documentation
- improve functional/task-level descriptions of some modes

I think all of this should be covered in other places, and many of our users are using things like `search-buffer`, `headings-panel` etc. to paginate around the manual/tutorial -- so I am closing this issue.
