### ISSUE TITLE
Support Chrome-based renderer

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#2989]
WebKitGTK has enabled us to mature Nyxt, but it is undeniable that its performance as a web renderer is subpar when compared to Chrome-based ones. This is particularly noticeable in resource intensive tasks such as watching a video on YouTube. 

Supporting new renderers is in itself beneficial since it puts Nyxt's API under the test. As a remainder, Nyxt is renderer agnostic.

To achieve this goal there are two alternatives: CEF or Electron. The former has proved to be tough to achieve, while the latter seems [promising](https://github.com/atlas-engineer/cl-electron). 

WebKitGTK will continue to be supported.

This move will also helps us to distribute Nyxt on MacOS and Windows.

**Comment by aartaka** [comment]
There's always QtWebEngine as yet another Chromium wrapper that's more or less ethical and modularized. Just that it's C++ and pain to bind to (⌒_⌒;)

**Comment by LinArcX** [comment]
Really? Electron? 

Did you measure performance?

**Comment by aadcg** [comment]
@LinArcX performance is certainly an important factor. But the ability to easily write Lisp bindings is actually the most important aspect to achieve this goal. 

Others can expand on the technical issues, if you'd like to :)

**Comment by aartaka** [comment]
Yep, ease of Lisp bindings is the main feature for us, because we don't have:
- A C++ person to make https://github.com/atlas-engineer/cl-webengine complete.
- A CEF-aware person to conform to all the opaque requirements that CEF sets up, mostly locking us to C :D

**Comment by fnicastri** [comment]
I really like the idea of Nyxt and I would like to be capable to use it on Mac but,
honestly, Electron would be a very bad choice.
Please don't.

**Comment by aadcg** [comment]
Would you like to expand?

**Comment by LinArcX** [comment]
I don't understand the word of "promising".

Guys you are not creating a toy tool. This is a browser.

We're living in a world that most people's work are migrating to web. So look at it as an operating system.

Performance matters and it matters a lot in your domian.

Please don't be hype with "promising" technologies.

**Comment by ILoveGoulash** [comment]
Are there numbers about the performance gap relevant to real world use? What about complexity (incl. bloat) or features (e.g. the recently talked about JPEG XL thing? Is supporting more than one implementation going to be a massive pain in the "glue" part of the code?

Not that, as a beggar, my questioning matters much, but personally, I'd focus on reaching a good "feature complete" (whatever that means; for most, it's having a proper (not hostfile based) adblocker) before thinking about such a big endeavour.

**Comment by aartaka** [comment]
> Guys, you are not creating a toy tool. This is a browser. We're living in a world that most people's work migrated to the web. So look at nyxt as an operating system.

We already do. And, much like an operating system doesn't care about the graphic chip or OpenGL version that's installed on one's machine (I'm somewhat exaggerating, but still), we don't really care about what renderer is there, as long as it works and allows us to build this exact Nyxt system.

> Performance matters and it matters a lot in your domian.

That's exactly why we look into Electron: it's basically Chromium torn apart to be embeddable anywhere. And, however painful it is to acknowledge that for me:
- Chromium is _the_ fastest and the most web-friendly web engine. 
  - Yes, that's because Google is a freaking monopolist enforcing their "vision" onto the Web.
  - Yes, it eats hella lot of RAM, but it fullfills its promises in runtime performance and rendering.
  - But it gives lots of benefits hard to achieve with any other engine:
    - Proper rendering of _any_ webpage.
    - Being cross-platform. Like, truly cross-platform.
    - And being easy to instrumentalize.

The notoriety of Electron is the consequence of it being used in a really wrong way: as GUI for desktop application. It's slow, it's resource-heavy, it's not really configurable and accessible... for a desktop GUI. It's intended to be a browser engine, not a GUI. And that's why we picked it as the renderer for Nyxt: it's a browser engine. Intended to be a basis for a browser, just gone astray into the land of desktop and wreaking havoc there.

---------------------------------------------------------------------------

As it's been already stated above, the main thing we look for in the new engine is ease of bindings and maintenance. So, if someone is religiously opposed to Electron (as a browser engine, not as a desktop GUI framework—because the latter I'm opposed to too) to a degree sufficient to spend their time helping us find alternatives and work on them—we'll be glad to accept any contribution. Two directions that we abandoned because of the terrible time we spent binding them were:
- QtWebEngine.
- and Chromium Embedded Framework.

So if someone has enough experience with these (or any other technology we're unaware of) to help us bind those to Nyxt, then I myself (and, likely, other team members too) will happily ditch Electron and help this person in making a better port for Nyxt.

But, until that happens, Electron is our best bet, given the resource/expertise restrictions we have on the team.

**Comment by fnicastri** [comment]
Thanks for the explanation, it makes more sense now.
Still hope one day another way will open...
Maybe Servo...?

Anyway can't wait to use it on Mac ;)

**Comment by Gavinok** [comment]
Have a look at servo on its own and you will see it's no where near ready. It's currently as slow as molasses and even less stable than WebKit.

I worked on porting it to Nyxt and it wasn't long before I realised it's a lost cause

**Comment by fnicastri** [comment]
What I meant was: maybe in the future Servo will be an option, I know it's not stable nor
workable for now.

**Comment by moumn-almunawy** [comment]
Why not use tauri?

**Comment by AlexanderMaxRanabel** [comment]
Its kind of a bummer that we cannot have browsers without Chromium these days

**Comment by ed9w2in6** [comment]
@AlexanderMaxRanabel 
It seems that Chromium is more secure though: https://madaidans-insecurities.github.io/firefox-chromium.html

And personally I found that Chromium looks better on across different OSs when compared to Firefox.

That being said I'm using a mac and the webkit-based Safari mostly.

**Comment by mckravchyk** [comment]
It's worth mentioning that [CEF is blocked by Google](https://lists.webkit.org/pipermail/webkit-dev/2020-November/031604.html) (sign ins) to protect against phishing in apps. Hopefully it does not happen to Electron.

**Comment by aadcg** [comment]
The Electron port is far from being finished, but a proof of concept has been made. For details see https://nyxt-browser.com/article/release-4.0.0-pre-release-1.org.

To address concrete issues about the Electron port please open new issues.


Closing.
