### ISSUE TITLE
Next is now available from homebrew

### ISSUE THREAD

**Issue by rpgoldman** [atlas-engineer/nyxt#299]
There's a Homebrew cask for `Next.app` now -- maybe add this to the list of ways to install next on MacOS?

**Comment by jmercouris** [comment]
Is it for the latest version of Next? I don't have Homebrew to confirm. If so, I'd be happy to add it to the README or merge a PR with that information.

**Comment by rpgoldman** [comment]
According to brew, this is version 1.3.0, which agrees with what is in the version of `next.asd` I checked out this morning.

**Comment by jmercouris** [comment]
No problem, your assessment is correct!

**Comment by seanfarley** [comment]
The Homebrew package is still at 1.2.1 even though someone changed it: https://github.com/Homebrew/homebrew-cask/pull/67260

I'm trying not to come off as rude since rpgoldman pointed that out but it would be nice if functionality was checked to be working before merging (more of a comment about homebrew-casks merging that PR).

**Comment by rpgoldman** [comment]
@seanfarley I'm not sure what is going on with brew.  I built from source, and had troubles. Now when I tried to reinstall from brew (even after removing the Caskroom copy and the dmg in my cache), next will not start and I get an error message saying that the application has been damaged.

I am not sure if this is a new copy that is bad, or if there is some configuration or other file left around that keeps the brew copy of next from opening.  Not finding anything helpful in the MacOS console.

**Comment by seanfarley** [comment]
Yeah, it's really mysterious to me as well. I'm hoping for guidance as well! And it's nice to know that someone else besides me is facing the same issues :-)

**Comment by rprimus** [comment]
Wed Aug 14 10:45:18 BST 2019

Just a FYI wrt the cask.

All the person did was update the version number of the cask.

The downloaded dmg still points to the previous dmg:
`https://next.atlas.engineer/static/release/next-macos-webkit.dmg`.   That's why the SHA did not change.

As noted at: https://next.atlas.engineer/download

> Next 1.3.0 is in beta for macOS and can only be currently installed via MacPorts or from source.

**Comment by jakevossen5** [comment]
What work needs to be done to get the cask up and running? I just installed the cask. I was able to open it, but it was pretty broken. My Meta key didn't work, and pressing Meta n caused it to crash.

**Comment by jmercouris** [comment]
Quite a lot, none of us use brew, and we are doing an architectural rewrite at the moment. So thank you for your offer to help, however we will hopefully have a greatly simplified process coming soon!

**Comment by aadcg** [comment]
I believe that this issue is severely outdated. None of the developers uses Homebrew.
