### ISSUE TITLE
Improve the descriptiveness of the hover text for lambda symbol in prompt buffer.

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#3002]
**Is your feature request related to a problem? Please describe.**
Button hover text should communicate the action as clearly as we can. The current hover text for the lambda button is "Execute", which might leave one with the question. Execute what?

**Describe the solution you'd like**
I propose updating the hover text to read "Execute-command Menu" to communicate that the button opens a menu. 

**Describe alternatives you've considered**
I considered "Execute Command Menu" --- however `execute-command` with the hyphen is the name of the invocation. So alluding to it seems more precise / consistent. 

**Additional context**
Thank you! :D

**Comment by aadcg** [comment]
Sounds sensible to me!

**Comment by aartaka** [comment]
The cool feature that Lisp Machines had was allowing the `Command Name` spelling in their command menu, instead of the underlying `command-name`. ~Well, not really, because they actually had commands exclusively called `Change Directory` 😅~

So what we can have is: 
- Allow using commands with spaced-capitalized spelling in the `execute-command` menu.
- Rewrite button titles to spaced-capitalized spelling.
- Profit!

**Comment by aadcg** [comment]
I don't see how that connects with the request from the top post.

**Comment by aartaka** [comment]
It doesn't, it's mostly off-topic. The only actionable thing here is: "Execute Command" could be a suitable text for the title.

**Comment by aartaka** [comment]
Gone with "Execute-Command Menu" then!
