### ISSUE TITLE
Set `spinneret:*suppress-inserted-spaces*` to `t`

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#3080]
Our docs  written with the help of `spinneret` suffer from minor whitespace issues. Find an example in the screenshot below.

![2023-07-12_19:13:54](https://github.com/atlas-engineer/nyxt/assets/45483512/184a099f-e1e3-41e5-bb5b-16588cc76006)

I suggest the solution below.

```lisp
> (spinneret:with-html-string (:p "Hello " (:span "World") "!"))
"<p>Hello <span>World</span> !"
> (spinneret:with-html-string (:p "Hello " (:span "World") " !"))
"<p>Hello <span>World</span> !"
> (let ((spinneret:*suppress-inserted-spaces* t)) (spinneret:with-html-string (:p "Hello " (:span "World") " !")))
"<p>Hello <span>World</span> !"
> (let ((spinneret:*suppress-inserted-spaces* t)) (spinneret:with-html-string (:p "Hello " (:span "World") "!")))
"<p>Hello <span>World</span>!"
```

**Comment by aartaka** [comment]
Interestingly enough, supressing spaces often causes the punctuation following a tag (e.g. `<span>hello</span>,`, but most noticeable with `<a>`) to somehow become part of the tag. Stumbled upon it while working on a personal website.

Although I'm not sure whether that's a behavior of rendering engines or Spinneret, because the latter seems to generate correct code 😕

**Comment by aartaka** [comment]
See 
- https://aartaka.me/drafts/weird-html.html for the rendering.
- https://aartaka.me/drafts/weird-html.lisp for the source (macro-heavy, but it's the paragraph that matters.
- And https://gitlab.com/aartaka/aartaka.gitlab.io/-/blob/master/tags.lisp#L411 for the function that generates it all, binding the dynamic vars like `*supress-inserted-spaces*`.

**Comment by aartaka** [comment]
I might've got it wrong at some level, so it might be me messing the HTML up 😛
