### ISSUE TITLE
Is Qt render alive?

### ISSUE THREAD

**Issue by catap** [atlas-engineer/nyxt#3118]
**Describe the bug**

An attempt to build Qt render failed with number of "missed" changes in API.

For example:
 - https://github.com/atlas-engineer/nyxt/commit/a8a8f2589c9605d1a09608341d93a8dae4633862
 - https://github.com/atlas-engineer/nyxt/commit/ee56effa4ceec47cdaad039b47dd704ad6c44781

After fixing this two it leads to
```
:info:build Unhandled UNBOUND-VARIABLE in thread #<SB-THREAD:THREAD "main thread" RUNNING
:info:build                                         {10013B0073}>:
:info:build   The variable WINDOW is unbound.
```
and I gave up here.

So, is it alive? or?

**Comment by jmercouris** [comment]
Qt render is effectively dead, we are hard at work on a cl-electron port if you would be so inclined as to help :-)

**Comment by jmercouris** [comment]
Qt had too many issues for us, that is why we are working on a different version. I wish it were easy, but finding a good renderer is really hard.

**Comment by catap** [comment]
@jmercouris well.. this seems quite interesting idea to be honest.

Help? I think I may able to help to port it to macOS. I've suceffuly build and run Nyxt-3.5.0 on macOS via MacPorts:

![image](https://github.com/atlas-engineer/nyxt/assets/37775/90fc2d52-d57f-4748-a30e-e4f155bffe33)

**Comment by barracuda156** [comment]
> Qt render is effectively dead, we are hard at work on a cl-electron port if you would be so inclined as to help :-)

@jmercouris Presumably that depends on NodeJS?

@catap How about fixing NodeJS over a weekend? We just need to rewrite the assembler…

**Comment by catap** [comment]
> @jmercouris Presumably that depends on NodeJS?

chromium + node :)

**Comment by barracuda156** [comment]
> > @jmercouris Presumably that depends on NodeJS?
> 
> chromium + node :)

Oh, so trivial to fix LOL

@jmercouris It is really desirable to have either Qt4 or Carbon backend working.

**Comment by catap** [comment]
@aadcg nope, I was just courious about it status because I've tried to build it at begining with Qt and after some time and fixing some "forgotten things"... well I've started to doubt that it works.

**Comment by catap** [comment]
Right now it simple doesn’t supported 🫣

**Comment by barracuda156** [comment]
@aadcg I merely replied to “Again, I'm eager to listen to the motivation behind the interest in Qt”. I won’t convince anyone here, especially if the matter is already decided.

QtWebKit exists back in Qt4, which works fine. Early versions of Qt5 should be fixable with moderate efforts. Fixing V8 requires rewriting assembler to begin with – and then fixing unknown number of bugs, because no one tested it on 32-bit Big-endian for years. So to me there is a difference.

> And what conclusion are you extracting from this fact?

I guess it is pretty obvious for anyone to arrive at :) But it is your project, and you can do whatever you wish with it, of course.
