### ISSUE TITLE
Describe-Slot -- Show current value

### ISSUE THREAD

**Issue by lansingthomas** [atlas-engineer/nyxt#3135]
Stop me if this is by design...

`describe-slot` shows a default value for a slot.

should it also show a current value for that slot?

@hgluka this came from a conversation we had so I am assigning you : )

**Comment by jmercouris** [comment]
The current value, for which object? I mean there could be an infinite amount of objects. In some cases it is obvious, like the current buffer object, but what about the ambiguous cases?

**Comment by hgluka** [comment]
I have to agree.
I like the idea, but now that I think about it, I don't know how feasible it is.

For example, there are slots like `current-zoom-ratio` or `modes` that can be different for each buffer. How do we pick the current value for those slots?
Another issue would be slots for classes like `prompt-buffer` that aren't always instantiated.

Maybe we could make the "current value" be the value of the slot in a brand new instance of a class. That's not always the same as the default value, since it can be changed with `define-configuration`, `configure-slot` or some other configuration methods.

What do you think? @jmercouris

**Comment by lansingthomas** [comment]
cool cool. Thx all.
