### ISSUE TITLE
Machine readable url annotations

### ISSUE THREAD

**Issue by Lamppilutti** [atlas-engineer/nyxt#3152]
**Is your feature request related to a problem? Please describe.**
I would like to be able to set some information to an url as a plists/alists. So then later I can use this information in my userscripts/packages for some automatisation like draw colored borders over html element if it associated with url what have `(:dislike t)` property or redirect when open if url have `(:redirect-to "other-redirect")` and so on.

**Describe the solution you'd like**
I found that the [annotations](https://github.com/atlas-engineer/nyxt/blob/master/source/mode/annotate.lisp) looks what I search, except that the `data` slot contains string. So I think there can be some `machine-data` slot in `annotation` class. Or class like `machine-annotation` which `data` will contains Lisp object. 

**Describe alternatives you've considered**
This can be a different subsystem, which exists exclusively for url metadata.

**Comment by aartaka** [comment]
Annotations are the closest we have to what you want, but they are somewhat simplistic at the moment, so no element matching or human-readable serialization. You might hack up something that works for your case, that'll be faster. 

But still, the issue is meaningful: we need to update our annotations both in semantics (#2247) and usability.

**Comment by jmercouris** [comment]
I don't believe we'll do this. In any case, it is not a priority.
