### ISSUE TITLE
FreeBSD 13.2 build failure

### ISSUE THREAD

**Issue by mutkach** [atlas-engineer/nyxt#3257]
FreeBSD 13.2-Release
SBCL 2.3.9

```
WARNING: redefining NYXT:EQUALS in DEFGENERIC
Unhandled SB-INT:SIMPLE-PROGRAM-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                   {1001A38113}>:
  invalid number of arguments: 2

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001A38113}>
0: (STR:REPLACE-ALL "C-" "C-space") [external]
1: (NKEYMAPS/CORE:PRETTY-BINDING-KEYS EXECUTE-COMMAND (#<NKEYMAPS/CORE:KEYMAP override-map {100A8CD703}> #<NKEYMAPS/CORE:KEYMAP document-mode-cua-map {1008FA9453}> #<NKEYMAPS/CORE:KEYMAP base-mode-cua-map {1009303A53}>) :TEST NIL :PRINT-STYLE "cua")
2: (BINDING-KEYS EXECUTE-COMMAND :MODES NIL)
3: ((FLET "<CODE>374" :IN #:|<SECTION#ID-VAR21>72|))
4: ((LABELS SPINNERET::INLINE-BODY :IN "/usr/home/nikita/common-lisp/nyxt/_build/spinneret/functions.lisp") #<unavailable argument>)
5: ((LABELS SPINNERET::PRINT-INLINE-TAG :IN "/usr/home/nikita/common-lisp/nyxt/_build/spinneret/functions.lisp") #<unavailable argument> #<unavailable argument> #<unavailable argument> #<unavailable argument> #<unavailable argument> #<unavailable argument> #<unavailable argument> #<unavailable argument> #<unavailable argument> #<unavailable argument>)
6: (SPINNERET.TAG::CODE #<unavailable argument> #<unavailable argument> #<unavailable argument> #<unavailable argument>)
7: ((FLET "<A>368" :IN #:|<SECTION#ID-VAR21>72|))
...
unhandled condition in --disable-debugger mode, quitting
;
; compilation unit aborted
;   caught 1 fatal ERROR condition
SLYNK's ASDF loader finished.
Compilation failed, see the above stacktrace.
```
How do I debug it further? I shortened the stacktrace a bit, I can provide it if it's needed.
is my understanding correct that `str:replace-all` and nkeymaps/keymap.lisp is the culprit here? Any ideas how to fix it for FreeBSD?

```
_build/nkeymaps/keymap.lisp:              (str:replace-all
_build/nkeymaps/keymap.lisp-               "M-" #+linux "Alt+" #+darwin "Option+" #+win32 "Alt+"
_build/nkeymaps/keymap.lisp:               (str:replace-all
_build/nkeymaps/keymap.lisp-                "S-" #+linux "Super+" #+darwin "Command+" #+win32 "Win+"
_build/nkeymaps/keymap.lisp:                (str:replace-all
_build/nkeymaps/keymap.lisp-                 "s-" #+linux "Shift+" #+darwin "Shift+" #+win32 "Shift+"
_build/nkeymaps/keymap.lisp:                 (str:replace-all
_build/nkeymaps/keymap.lisp-                  "C-" #+linux "Ctrl+" #+darwin "Ctrl+" #+win32 "Ctrl+"
_build/nkeymaps/keymap.lisp-                  i)))))
_build/nkeymaps/keymap.lisp-            (binding-keys bound-value keymap-or-keymaps :test test))))
```

**Comment by mutkach** [comment]
> @mutkach you're correct. The issue here is that you're building for FreeBSD and none of the reader macros matches it. Could you share the output of `sbcl --non-interactive --eval '(print *features*)'`?
> 
> I think what we should do here would be to have the reader macro match `darwin` and `win32` and have a safe fallback otherwise.

```
(:ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT
 :ANSI-CL :BSD :COMMON-LISP :ELF :FREEBSD :IEEE-FLOATING-POINT :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS
 :SB-THREAD :SB-UNICODE :SBCL :UNIX)
```

**Comment by mutkach** [comment]
Thanks a lot! It works now!

**Comment by mutkach** [comment]
Thanks a lot again, `nyxt` seem to work just fine. There seems to bit some minor problems ahead - in that case will it be appropriate to open a new issue or should I proceed with this one, as these issues seem to be pretty specific to FreeBSD?

**Comment by baulig** [comment]
I've seen the same issue on the FreeBSD 14 preview as well and just tried building it on OpenBSD 7.4.

On OpenBSD 7.4 with the SBCL 2.3.8 that came with it, that `sbcl` command yields

```
(:ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT :ANSI-CL :BSD :COMMON-LISP :ELF
 :IEEE-FLOATING-POINT :LITTLE-ENDIAN :OPENBSD :PACKAGE-LOCAL-NICKNAMES
 :SB-CORE-COMPRESSION :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE :SBCL
 :UNIX)
 ```
 
 Applying the above-mentioned patch with `openbsd` added to it gets it to build (with a minor `libfixposix` patch).  However, it won't start:
 
 ```
 $ ./nyxt --failsafe
failed to allocate 1048576 bytes at 0x20000000
(hint: Try "ulimit -a"; maybe you should increase memory limits.)
```

That issue looks familiar to me; I vaguely remembered that I had patched something in SBCL in the past that got me past the issue.  I'll investigate this a bit further and also reboot into my new FreeBSD system.

**Comment by baulig** [comment]
Just tried with the latest FreeBSD 14.0-RC3 and it builds fine with the above patch.

I'm getting some warnings on launch:

```
 ./nyxt
WARNING:
   Type initializer for class 'WebKitURISchemeResponse' (GType 'WEBKIT-URI-SCHEME-RESPONSE') is invalid: foreign symbol 'webkit_uri_scheme_response_get_type'
Nyxt version 4
<INFO> [21:34:09] Source location: #P"/usr/Workspace/External/nyxt/"
<WARN> [21:34:09] Warning: Error on separate thread: Can't create directory /usr/Workspace/External/nyxt/nyxt,
a file with the same name already exists.
<INFO> [21:34:09] GTK extensions directory: #P"/usr/Workspace/External/nyxt/libraries/web-extensions/"

(nyxt:83988): Gtk-CRITICAL **: 21:34:09.389: gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed
<INFO> [21:34:09] GTK extensions directory: #P"/usr/Workspace/External/nyxt/libraries/web-extensions/"
<INFO> [21:34:09] Loading #P"/usr/home/martin/.local/share/nyxt/history/default.lisp".
<INFO> [21:34:09] Restoring 1 buffer from history.
<INFO> [21:34:09] Loading #P"/usr/home/martin/.local/share/nyxt/auto-rules.lisp".
<WARN> [21:34:09] Warning: Error while routing "nyxt" resource: The alien function "webkit_uri_scheme_response_new" is undefined.
<WARN> [21:34:09] Warning: Error while routing "nyxt" resource: The alien function "webkit_uri_scheme_response_new" is undefined.
<INFO> [21:34:09] Failed to load URL nyxt:new in buffer 2026.
<WARN> [21:34:09] Warning: Error while routing "nyxt-resource" resource: The alien function "webkit_uri_scheme_response_new" is undefined.
```

It won't load the `nyxt:new` page, but I can enter an URL - such as for instance this GitHub issue page and it loads.

I suppose this is due to a version incompatibility with WebKit; FreeBSD 14 comes with `webkit2-gtk3-2.34.6_8`.

Still no luck with OpenBSD - but it's working fine in my GNU Guix VM with Flatpak.

**Comment by baulig** [comment]
@aadcg I'm currently trying to build the latest WebKitGTK (2.43.1) to build on FreeBSD; it looks like this requires some manual patching.  If I can get that to work, then I'll contact the maintainer and ask whether the official port could possibly be updated.

Regarding OpenBSD, that's quite a bit more complicated - but I have some time next week and will see what I can do.

**Comment by baulig** [comment]
@aadcg Does Nyxt support GTK 4 (preferably without Wayland because I'm using XMonad)?

FreeBSD 14-RC3 has a GTK4-version of WebKitGTK 2.38.3, only the GTK3 one is outdated.

Unfortunately, building WebKitGTK on any of the BSD's is quite a challenge - and the patches from the ports tree often won't apply anymore with even the next minor version.

After spending a couple hours trying to get various different versions to build - and always running into some obscure C++ issues - I copied the patches from the GTK4 version onto the GTK3 one.

That finally got me a `webkit2-gtk3-2.38.3_9` package.

However, I must have done something wrong because after a full rebuild of Nyxt, it just hangs on startup.

```
[martin@rohan:nyxt % 1862] $ ./nyxt --system-info
Nyxt version: 4
Renderer: GI-GTK
Operating system kernel: FreeBSD 14.0-RC3
Lisp implementation: SBCL 2.3.8 (Dynamic space size: 3221159936)
Features: (:NYXT-GI-GTK :NYXT-GTK :NYXT-GI-GTK :NYXT-GTK :NYXT-4
 :CLIPBOARD-CONTENT-METHOD :SWANK :SLYNK :PLUMP-UTF-32 :PARENSCRIPT :NSYMBOLS
 :FSET-EXT-STRINGS :NAMED-READTABLES :GLOBAL-VARS :CL-FAD :LPARALLEL
 :21BIT-CHARS :CUSTOM-HASH-TABLE-NATIVE :CL-PPCRE-UNICODE :CL-UNICODE :CHUNGA
 :FLEXI-STREAMS :CL-PPCRE :WEBKIT2 :WEBKIT-2.38.3 :WEBKIT-2.38 :WEBKIT-2
 :WEBKIT2-CORS-ALLOWLIST :WEBKIT2-PASTE-PLAINTEXT :WEBKIT2-TRACKING
 :WEBKIT2-MUTE :WEBKIT2-EMOJI :WEBKIT2-MEDIA :WEBKIT2-SANDBOXING :GTK-3-22
 :GTK-3-20 :GTK-3-18 :GTK-3-16 :GTK-3-14 :GTK-3-12 :GTK-3-10 :GTK-3-8 :GTK-3-6
 :GTK-3-4 :GTK :GDK-3-22 :GDK-3-20 :GDK-3-18 :GDK-3-16 :GDK-3-14 :GDK-3-12
 :GDK-3-10 :GDK-3-8 :GDK-3-6 :GDK-3-4 :CAIRO-1-10 :CAIRO-1-12 :GDK-PIXBUF
 :CLOSER-MOP :GLIB-2-30 :GLIB-2-32 :GLIB-2-34 :GLIB-2-36 :GLIB-2-38 :GLIB-2-40
 :GLIB-2-42 :GLIB-2-44 :GLIB-2-46 :GLIB-2-48 :GLIB-2-50 :GLIB-2-52 :GLIB-2-54
 :GLIB-2-56 :GLIB-2-58 :GLIB :BORDEAUX-THREADS :LPARALLEL.WITH-CLTL2
 :LPARALLEL.WITH-CAS :LPARALLEL.WITH-STEALING-SCHEDULER :SPLIT-SEQUENCE
 CFFI-FEATURES:FLAT-NAMESPACE CFFI-FEATURES:X86-64 CFFI-FEATURES:UNIX :CFFI
 CFFI-SYS::FLAT-NAMESPACE ALEXANDRIA::SEQUENCE-EMPTYP :FAST-IO-SV :FAST-IO
 :CL-JSON-CLOS :CL-JSON :SBCL-USES-SB-ROTATE-BYTE CHIPZ-SYSTEM:GRAY-STREAMS
 :THREAD-SUPPORT :ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT
 :ANSI-CL :BSD :COMMON-LISP :ELF :FREEBSD :IEEE-FLOATING-POINT :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE
 :SBCL :UNIX)

ASDF version: 3.3.1
ASDF registries: (NYXT-SOURCE-REGISTRY ENVIRONMENT-SOURCE-REGISTRY)
Critical dependencies: (/usr/Workspace/External/nyxt/_build/cl-cffi-gtk/gtk/cl-cffi-gtk.asd
 /usr/Workspace/External/nyxt/_build/cl-gobject-introspection/cl-gobject-introspection.asd
 /usr/Workspace/External/nyxt/_build/cl-webkit/webkit2/cl-webkit2.asd)

[martin@rohan:nyxt % 1863] $ ./nyxt --failsafe
Nyxt version 4
<INFO> [00:37:38] Source location: #P"/usr/Workspace/External/nyxt/"
<INFO> [00:37:38] Profile: "nofile"
```

At that point, I have to `kill -9` it.

**Comment by baulig** [comment]
This is on FreeBSD 14:

```
$ sbcl --non-interactive --eval '(print *features*)'
This is SBCL 2.3.8, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
;;; loading #P"/usr/local/lib/sbcl/asdf/asdf.lisp"

(:ASDF3.3 :ASDF3.2 :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
 :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ARENA-ALLOCATOR :X86-64 :GENCGC :64-BIT
 :ANSI-CL :BSD :COMMON-LISP :ELF :FREEBSD :IEEE-FLOATING-POINT :LITTLE-ENDIAN
 :PACKAGE-LOCAL-NICKNAMES :SB-LDB :SB-PACKAGE-LOCKS :SB-THREAD :SB-UNICODE
 :SBCL :UNIX)
 ```
 
> > Does Nyxt support GTK 4 (preferably without Wayland because I'm using XMonad)?
> 
> It doesn't and it may be a time-consuming task. See #3259.
> 
> @baulig contact the BSD maintainers, maybe they can help to update webkitgtk for GTK 3. Ideally, it should be bumped to the latest stable version - 2.42.2.

Okay, looks like we need to get a working WebKit for GTK 3, then.  Since I have just blindly picked the patches from the GTK 4 version, chances are that my webkit package is just broken.

**Comment by shamazmazum** [comment]
@baulig You can build a fresh version of webkit for gtk3 using my port (but read `README.md` first):
https://github.com/shamazmazum/freebsd-ports/tree/master/www

But you need to rebuild all your ports for that :) You can do this with poudriere if you have time.

**Comment by t-zuehlsdorff** [comment]
Aloha,

i have written a port for Nyxt, compiling on FreeBSD 13.x and 14.x. It works and starts fine so far, but is of course hit by the gtk issue.

There is currently an big afford ongoing to bring all the GTK ports to a current version: 
* https://reviews.freebsd.org/D45878
* https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=275914

If you would like to help, feel free to join :)  

And if you are interested in the Portfile, please let me know. I would share it happily for further testing. If we can fix the issues, i will commit it and we can have Nyxt even as a binary package available using "pkg install" :)  

Best,
Torsten

**Comment by aadcg** [comment]
@t-zuehlsdorff thanks for your interest and time.

A couple of things that may help you.

If you're trying to compile WebKitGTK, it is a good idea to pass the flag `-DENABLE_MINIBROWSER=ON`. It outputs a minibrowser that can be used to validate the build.

Nyxt tracks stable WebKitGTK releases, i.e. those whose minor version have even numbers (2.44.x, 2.46.x, etc).

Nyxt requires the `libwebkit2gtk-4.1.so` shared library (not 6.0) and uses GTK3, i.e. WebKitGTK is compiled with flag `-DUSE_GTK4=OFF`.

Note that @shamazmazum did his own port, so make sure that your effort isn't redundant.

**Comment by t-zuehlsdorff** [comment]
Aloha @aadcg,

thank you for the pointer. The tips are great :)  

But I won't have the ability to pass several compiler flags around. I want to port Nyxt into the Ports Ecosystem of FreeBSD. This way an installation would be a simple `pkg add www/nyxt` and everything is done. Therefore i need to work with the existing Infrastructure (or adjust it). This already works well, besides the ancient version of WebKitGTK.

I think this is the best approach for both projects. It would be the easiest and best integration into FreeBSD. We also have a "upstream first" policy. So when Nyxt gets adopted and issues should arise, patches will be written and proposed to you. 

My current port are the typical 4 files of the ports tree. If you want to build it on your system, you just enter the dir and call "make install" and everything else is done for you. :) I could already prepare a binary package, so it would be a simple "pkg add nyxt-3.11.7.xz" and everything else is done for you. :)  

BTW i found the copy & paste issue. It is located in the trivial-clipboard lib, which assumes there must be a Window Manager. Since i am using a Tiling Manager, it finds xclip and throws its findings away.

**Comment by shamazmazum** [comment]
@t-zuehlsdorff I doubt Nyxt can be easily packaged for FreeBSD. It depends on how it is distributed. I usually build from a git tag or branch. If you also wish to build Nyxt from a tag, you'll have to provide `GH_TUPLE` for all of its dependencies (submodules) in your Makefile. It is really painful, as there are 153 of them (for v3.11.7).

Another way: find a way to package every needed asdf system and make a dependency on that system. Maybe it can be automated to some extent, like we have `USE_PYTHON= autoplist` for python.

In any case, `www/webkit2-gtk3` should be upgraded first. FreeBSD has an old version (2.34.6) which will not work with Nyxt. I posted a link to my own port for Webkit, but it requires the whole base system and ports to be recompiled, so this is not a general solution. Currently, I use Webkit 2.42.4 (2.44.0 crashes for some reason).

Offtopic question to Nyxt developers: Have you tried to use qlot to control dependencies instead of git submodules?

**Comment by aadcg** [comment]
> I usually build from a git tag or branch. If you also wish to build Nyxt from a tag, you'll have to provide `GH_TUPLE` for all of its dependencies (submodules) in your Makefile. It is really painful, as there are 153 of them (for v3.11.7).

It seems that the packaging system of FreeBSD lacks a painless way to build from a git reference. Nonetheless, only tagged releases should be packaged and, in that setting, the proper way to build is from the published tarball which contains all Common Lisp dependencies. 



> The easiest way: if there is an archive with all dependencies packed alongside with the sources, then you possibly should use that archive.

Exactly. 

> Offtopic question to Nyxt developers: Have you tried to use qlot to control dependencies instead of git submodules?

What would we gain from it? We need is a way to declare our "truth" regarding dependencies' versions, independent of any other external agent(s). The git submodules is our "truth" table, from which we generate self-contained tarballs with all CL sources bundled together. That makes the packaging process trivial for virtually any package manager since there's no need to package CL dependencies or rely on external tools.

**Comment by shamazmazum** [comment]
> It seems that the packaging system of FreeBSD lacks a painless way to build from a git reference.

Nope, you can use `USE_GITHUB` for building from a git repo on github. But, you need to specify commit hashes for each submodule because interacting with the web is prohibited during a build, so you cannot do `git submodule update --init`.

> the proper way to build is from the published tarball which contains all Common Lisp dependencies.

Yes, I see that there is such tarball, so it should be easy.

> What would we gain from it?

Personally, I have to make `git submodule update --init` and `rm local-projects/system-index.txt` before any interaction with Nyxt sources and `git submodule deinit --all` and `rm local-projects/system-index.txt` after. Not very convenient.

**Comment by shamazmazum** [comment]
All in all, I would recommend  to solve the problem with outdated `www/webkit2-gtk3` globally, then making a port of nyxt. Or try a new electron renderer, FreeBSD has versions from 27 to 30

**Comment by aadcg** [comment]
This is off-topic indeed but, since we're touching the subject, it's better to clarify it.

> Nope, you can use `USE_GITHUB` for building from a git repo on github. But, you need to specify commit hashes for each submodule because interacting with the web is prohibited during a build, so you cannot do `git submodule update --init`.

It is a pre-build operation, when the sources are fetched. Instead of doing a `git clone ...`, a `git clone --recurse-submodules ...` is required. The build process itself doesn't rely on any git commands. Perhaps it used to do that in the past, but I have fixed that piece of nonsense.



> Personally, I have to make `git submodule update --init` and `rm local-projects/system-index.txt` before any interaction with Nyxt sources and `git submodule deinit --all` and `rm local-projects/system-index.txt` after. Not very convenient.

I don't understand what is the `system-index.txt` file you mention. Some details are missing so it's hard to give good advice. For instance, what is the goal? Given a git commit, do you want to generate a local binary or start Nyxt from the REPL? Feel free to send me an email for tips, since your workflow seems subpar to me.


-------



> I would recommend to solve the problem with outdated `www/webkit2-gtk3` globally

@shamazmazum this is the correct conclusion. It makes no sense to discuss anything else until FreeBSD doesn't package a recent WebKitGTK version. 

As mentioned, supporting FreeBSD isn't a priority or an effort we would like to officially support. We can help and give advice of course. Free free to re-open in case there are new developments. Thanks.

**Comment by shamazmazum** [comment]
> I don't understand what is the `system-index.txt`

Just to answer that question: It's a file created by quicklisp which stores a list of local systems. Nyxt with its submodules makes a lot of systems which are normally installed from quicklisp or ultralisp repositories local. So you have to remove that file after you've done hacking with Nyxt.

> It is a pre-build operation, when the sources are fetched.

FreeBSD ports do not work this way. Internally, the ports system fetches a list of explicitly listed files and checks their hashes against the hashes listed in `distinfo`. It's about security: this way you are sure that you have downloaded what you want.

>  It makes no sense to discuss anything else until FreeBSD doesn't package a recent WebKitGTK version.

Agreed. Theoretically, I can provide some support for @t-zuehlsdorff, but only when webkit is updated.

**Comment by t-zuehlsdorff** [comment]
Aloha Guys,

i just want to add to your discussion: you realize that I already did all the work for the port, right? ;)

You can see the prototype here:  
https://gitlab.p.variablis.de/open-source/freebsd-ports-tree/-/tree/nyxt/www/nyxt?ref_type=heads

Currently, it only lacks the WebKitGTK update and some proper testing. It builds and starts just fine in the supported FreeBSD versions. And for the WebKitGTK Update, there is already a patch proposed, to bring it to 2.44.2: https://reviews.freebsd.org/D45878

So when webkit is updated, we can go into more detail :)

[Yes, creating the list of Submodules from Github, Gitlab, and one Gitea Instance was a bummer, but i simply wrote a small script for it. In the end, i only needed to fix 3 Modules manually :) I plan to port this script to Lisp, since i try to start in Lisp since years.  ]

**Comment by aadcg** [comment]
> Yes, creating the list of Submodules from Github, Gitlab, and one Gitea Instance was a bummer, but i simply wrote a small script for it.

I'm sorry that you had to endure the tedious task. Please note that this strategy isn't future proof. We bump submodules on every release so, as mentioned above, the correct approach is to use the source published in each release. See https://github.com/atlas-engineer/nyxt/releases (`nyxt-3.11.7-source-with-submodules.tar.xz`).

**Comment by t-zuehlsdorff** [comment]
> I'm sorry that you had to endure the tedious task. 

No need to. Besides some practicing, I now have a script, which does this automatically. So it pays off with the next port :)

> We bump submodules on every release so, as mentioned above, the correct approach is to use the source published in each release.

That is way better. I will switch to this method when the GTK Update is done :)

**Comment by nunotexbsd** [comment]
Since FreeBSD have webkit2gtk updated, some tests could be done with port:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=284258

Somehow I can't make it find `libwebkit2gtk-4.1.so`

Unable to load any of the alternatives:
   ("libwebkit2gtk-4.1.so.0" "libwebkit2gtk-4.1.so" "libwebkit2gtk-4.0.so.37"
    "libwebkit2gtk-4.0.so")

**Comment by aadcg** [comment]
@nunotexbsd does `LD_LIBRARY_PATH` point to those shared libraries?

**Comment by t-zuehlsdorff** [comment]
@aadcg Yes, it does. It seems that SBCL can't find webkit, when SBCL is compiled with clang and webkit with GCC. We currently investigating this route.
