### ISSUE TITLE
Void Linux: Load libssl and libfixposix versioned library files at runtime

### ISSUE THREAD

**Issue by 0x0f0f0f** [atlas-engineer/nyxt#406]
**Describe the bug**
Im building next for void linux using xbps-src. It builds correcty. libressl and libfixposix packages for void provide a versioned library file (for example `libfixposix.so.3`) but when installed, next tries to load the library file without the version number (`libfixposix.so`). The correct symlink (`libfixposix.so => libfixposix.so.3`) is provided by the `-devel` packages which include development files for the libraries in question.

As a workaround I had to add `libfixposix-devel` and `libressl-devel` to the `next` package dependencies. Development dependencies should not be needed when installing the binary release of next from the Void Linux repositories.

To fix the bug next should load the libraries from the versioned library file at runtime.

**Precise recipe to reproduce the issue**
I'll comment as soon as i push the package template to my void-packages fork

**Information**
- OS name+version: Void Linux
- Kernel name+version: : Linux 5.2
- Desktop environment / Window manager name+version: i3wm not related
- Next version (from =M-x next-version= or =next --version=): 1.3.2
- How you installed Next (Guix pack, package manager, build from source): built from source
- SBCL version (if built from source): 1.5.6
- WebKitGTK+ / PyQt-Webengine version: 2.26.0

**Comment by Ambrevar** [comment]
Thanks for reporting, and most importantly thanks for packaging Next for Void Linux! :)

A couple of notes:
- Next does not load those libraries, it's the Common Lisp libraries that it depends on that do.  So there is nothing we can do here.

- If you want, you can patch cl-iolib to point to libfixposix.so.3.  Same for all the CFFI-based Common Lisp libraries the depend on third-party libraries.  (We kind of do that for Nix and Guix.)

- The choice to split between "-devel" packages and the  choice to place unversioned libraries in different places belongs to Void Linux.  (Not all distros do that.)  So in my understanding it also belongs to Void Linux to package libraries like cl-iolib in a way that works for the distro.

So what can you do?  Well, the simplest is to depend on the -devel libraries.
Otherwise:

- Either you run `make deps` to load all the deps via Quicklisp, then you patch the offending files that are located in `quicklisp/dists/quicklisp/software/`.

For instance, to fix libfixposix, you need to patch
 `quicklisp/dists/quicklisp/software/iolib-v0.8.3/src/syscalls/ffi-functions-unix.lisp`:

```patch
(eval-when (:compile-toplevel :load-toplevel :execute)
  (define-foreign-library libfixposix
-   (t (:default "libfixposix")))
+   (t (:default "libfixposix.so.3")))
  (use-foreign-library libfixposix)
```


- Or, if you really want to do it the neat way: package the CL libraries for Void Linux.  This is quite a lot of work since Next has some ~ 80 libraries.  Not all of them depend on CFFI though, so you might end up with only some 20 libraries to packages.

Does that make sense?
Let me know if you need some guidance :)

**Comment by jmercouris** [comment]
Closing this since Nyxt has been packaged for void Linux now. Please reopen if you have any issues!
