### ISSUE TITLE
Request: offer to install the missing optional programs

### ISSUE THREAD

**Issue by vindarel** [atlas-engineer/nyxt#436]
Next relies on some external programs: [keepassxc](https://keepassxc.org/) or [pass](https://www.passwordstore.org/) for the password manager, youtube-dl for the default video downloader, notify-osc (linux) or terminal-notifier (macos) and, well, git for M-x git-clone.

It would be nice if Next suggested to install those if they were missing, at the first call, and do it in the background. Specially the password utility.

Examples of dealing with external processes exist in the code: checking if a program exists (`executable-find`), capture the output (synchronously: `run-program-to-string`), wait for the exit code of an async process into a thread (`launch-and-notify`), use a channel to send and show messages across threads (cf the download manager),…

The developer can easily try things out in the REPL, even without loading Next to begin with. An external library would be best.

- documentation exists, to be completed if required: https://lispcookbook.github.io/cl-cookbook/os.html and https://lispcookbook.github.io/cl-cookbook/process.html

(instead of needing python for youtube-dl, we could use binaries of other programs, if they're good enough. I'm thinking about https://github.com/iawia002/annie)

**Comment by jmercouris** [comment]
How would this work on macOS?

**Comment by cbbrowne** [comment]
It would be a good start to have documentation as to what needs to be set up in order to get the keepassxc/pass integration working, which I imagine includes:

- Having the software installed
- Making Next aware of where it is (which it does try to do)
- Making Next aware of where the data file (e.g. - password file) is
- Attaching key bindings for useful things (e.g. - launching it, which might be automatic, submitting the password to open the wallet, requesting passwords from the wallet, perhaps requesting userIDs from the wallet, and generating passwords to put into the wallet...)

It's possible some portion of the work can be automated, so it would go into the code base; some portions most likely remain in init.lisp...

**Comment by tviti** [comment]
On macOS, you'd have to make sure that you're installing `pinentry-mac` (which provides a native gui for password entry), since from what I can tell, the cli `pinentry` program doesn't actually work with next (hence when trying unlock the gpg-key, `uiop:run-program` will just throw an error at the SBCL repl).

This also means that next would have to configure `.gpg-agent` to use `pinentry-mac` instead of `pinentry`, which I think might be classed under `undesirable side-effect` (although it would be reasonable to bring up a message in the minibuffer telling the user how to configure everything).

**Comment by Ambrevar** [comment]
Next installing packages sounds like we would have to write... A
universal package manager :)

Which is not that big a deal, after all Emacs got one:

https://github.com/emacs-helm/helm-system-packages

(Note that the above has some architectural flaws.)

**Comment by vindarel** [comment]
just open-sourced UPM: https://github.com/replit/upm works for language dependencies OS-agnosticly, but it doesn't install system software, apparently.

**Comment by aadcg** [comment]
I don't see the point in implementing this feature because I think we're identifying the problem wrongly. If a specific feature in Nyxt requires the use of an external program, then an error must be printed out. Most likely, `uiop:run-program` already does it. The user is then responsible to take action based on the error message.

The topic of package management is already being discussed on #131.
