### ISSUE TITLE
How do I actually start the browser?

### ISSUE THREAD

**Issue by togakangaroo** [atlas-engineer/nyxt#481]
I feel like this is a stupid question but I've not used macports before.

I followed the instructions, got it running, then did

> sudo port install next

(Suggestion 1: Yall just say in the docs to "install from macports" but not the actual name of the thing to install! - I'm still not sure that `next` was the right thing.)

Now....what am I actually supposed to do afterwards?

I don't see any new executables named `next` so - how do I run it?

How do I run it inside emacs? I assume there's some sort of package to install maybe? But which one?

(Suggestion 2: I think maybe we need a paragraph on the above)

**Comment by jmercouris** [comment]
Hi, no worries :-)

There should be an application bundle in `/Applications`, it will be called `Next.app`. This is currently a problem, but the next release of Next will be as a downloadable application bundle, so it shouldn't be too bad. In either case, the echo message upon successful installation of Next in MacPorts could be a little bit more helpful!

You can't run (at this time) Next within Emacs, though that would be quite cool...

**Comment by oscarfroberg** [comment]
No worries @togakangaroo, it took me way longer than that, and I'm not even there yet.

Took me probably half an hour to decipher the installation instructions, having never used Macports before, only Homebrew (turned out the issue was trying to install it in/from a home directory, not `/private/tmp`). And now the installation has taken 1h10m, *so far*, taking up 3 GB of space...

Might not be Next's fault, but certainly doesn't seem like a "lightweight browser" to me in this regard. 🙄
