### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by travankor** [atlas-engineer/nyxt#504]
I'm not sure if this is a goal or milestone that the next developers want to pursue, but [libhandy](https://source.puri.sm/Librem5/libhandy) allows WebkitGTK-based browsers to work well on space-constrained devices, like the [PinePhone](https://store.pine64.org/?product=pinephone-braveheart-limited-edition-linux-smartphone-for-early-adaptor) or Librem 5.

I think for browser projects that are solely focused on _just_ keyboard keybindings (like the vi*-influenced browsers), there would be very little benefit to have such a browser on a touchscreen device. I could see a more compelling argument for an Emacs-like browser, where extensibility is the primary feature, and it would be nice to have the same browser features and configuration for both desktop/laptop and touchscreen style workflows.

Granted, I don't know what the technical challenges are so this is all hypothetical :).
Currently only GNOME Browser (née Epiphany) is pursuing integration with libhandy.

**Comment by Ambrevar** [comment]
Mobile support is probably way down the road, but
this is very nice, thanks for sharing!

**Comment by aadcg** [comment]
In my personal opinion, I don't see how a program can be powerful if the user interacts with it with a touchscreen. It makes sense for short sessions, but it doesn't scale. Regardless, further down the road, I think this would be indeed interesting.

Touchscreens aside, having mobile support is desirable since connecting your mobile device into an external physical keyboard gets you a modest hacker station :p

It is theoretically possible to run Nyxt on Termux with some work. If anyone is interested, I can expand on that.

**Comment by aadcg** [comment]
It is possible to run Nyxt on Termux.

**Comment by jmercouris** [comment]
I don't think this is within our focus, but thank you for sharing.
