### ISSUE TITLE
Embed documentation

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#623]
We need to embed the full documentation (manual, extensions, developers readme) and make it accessible from within the browser, offline.

Then bind `C-h r`, `C-h t`, `C-h i`.

The easy fix: Export the manuals to HTML at compile-time and package the result with next.

The better fix: Use cl-org and render the Org files directly.

Result could look like https://orgmode.org/manual/index.html.
With a "documentation-mode" we could have Emacs' Info-style bindings.

**Comment by jmercouris** [comment]
`cl-org` does not have enough facilities to reliably render Org mode files, it only does some parsing. In this case we would have to more or less implement the whole org standard. Probably, we could implement what we need in a reasonable amount of time, instead of supporting everything. Another option, maybe we could make an elisp runtime that can run all of the org mode -> html code?

I think the easy fix will have to suffice for some time. We can have it as one of the build options to pass a command line tool to generate the org mode HTML output, whether that be pandoc, or emacs itself.

**Comment by Ambrevar** [comment]
Now that we've got `describe-*` commands for almost everything, the main thing that we miss is an embedded tutorial / manual.  Maybe a short tutorial using cl-markup with pointers to the various `describe-*` invocation would be good enough.

Then no need to convert the Org document.

Finally, what about moving the ChangeLog to a cl-markup file as well?

**Comment by jmercouris** [comment]
That is a good solution! I can move the changelog to markup as well, and then we can have a command in the program as well M-x changelog!

**Comment by jmercouris** [comment]
I'll take the opportunity to unify the style of the changelog when converting to markup

**Comment by jmercouris** [comment]
The documentation is now embedded.

**Comment by Ambrevar** [comment]
See #865 for a follow up on including the changelog.
