### ISSUE TITLE
Building master branch on NixOS

### ISSUE THREAD

**Issue by DieracDelta** [atlas-engineer/nyxt#753]
Hello! I'd like to run the master branch of `next` on my nixos box. I realize that a package already exists, but this package is for `next` version 1.5, which seems to be far away from the current master branch. 

I cloned the master branch (currently at commit `df6059fb1900ecaf8cd4bd4643101362b6821995`). Then I created [this shell.nix](https://gist.github.com/DieracDelta/f79c3928782852602dda52c294991fc1) and `nix-shell shell.nix`-ed into it. Then I ran `make all`. This successfully builds the binary, but when I try to open a url, I get the following error: `TLS/SSL support not available; install glib-networking`. I've made sure that `glib-networking` is on my `LD_LIBRARY_PATH` at runtime, so I'm not really sure what to do next here. Any advice would be appreciated!

Alternatively if someone has managed to build this for NixOS already, please share your script!

**Comment by DieracDelta** [comment]
As an update on this, it turns out the fix in issue #592 is the same issue I'm experiencing. Setting `GIO_MODULE_DIR` fixed the problem for me.

I'm going to remove a bunch of the janky stuff my derivation does and see if I can accomodate this. Would you guys be open to a PR that adds my (perhaps still janky) nix build to the `scripts/` directory?

Also, it might be helpful for new users to know that `GIO_MODULE_DIR` must be set. Thoughts on adding this as a blurb to the documentation? Perhaps as an aside in the developer readme?

**Comment by jmercouris** [comment]
I would gladly add such a file into our build-scripts directory :-)

thank you for your continued investigation on this topic!

PRs also welcome for the documentation :-)

thanks for your very detailed report!

**Comment by Ambrevar** [comment]
DieracDelta <notifications@github.com> writes:

> As an update on this, it turns out the fix in issue #592 is the same issue I'm experiencing. Setting `GIO_MODULE_DIR` fixed the problem for me.

If you look at the build-scripts/guix.scm file, you'll find all you need
to know for Nix since Guix and Nix are very similar in this regard.

> I'm going to remove a bunch of the janky stuff my derivation does and see if I can accomodate this. Would you guys be open to a PR that adds my (perhaps still janky) nix build to the `scripts/` directory?

Yes!  We can also ping the Nix package maintainer to prepare an updated
definition for the upcoming 2.0 release.

> Also, it might be helpful for new users to know that `GIO_MODULE_DIR` must be set. Thoughts on adding this as a blurb to the documentation? Perhaps as an aside in the developer readme?

This is an implementation detail that mostly concerns Nix and Guix
only.  With both recipes I don't think we need to bother other users
with this detail.

**Comment by walseb** [comment]
I have been trying to get the nyxt master branch building on nixos and while the method described (manually git-cloning nyxt and building it with this nix-shell file) seems to work, building it as a package doesn't. The root of the problem is that `cl-containers` is not available on nixpkgs (unless I'm mistaken). You could get the package using quicklisp like I believe is done when you build manually using the nix-shell approach, but when building a nix package you don't have internet access so that the builds are reproducible. 
To clarify, I get this error when building:
```
debugger invoked on a ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread
#<THREAD "main thread" RUNNING {10005184C3}>:
  Component :CL-CONTAINERS not found, required by #<SYSTEM "nyxt">
```

**Comment by Ambrevar** [comment]
As far as I know, Nix already provides a good bunch of Common Lisp
packages.  What would it take to add cl-containers?  It should not be
too hard.

**Comment by walseb** [comment]
This is strange, so apparently nix already builds all packages that are on quicklisp, including `cl-containers` : https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/lisp-modules/quicklisp-to-nix-output 

But I can't find it on nixpkgs: https://nixos.org/nixos/packages.html?channel=nixos-20.03&query=cl-containers

**Comment by bqv** [comment]
https://github.com/NixOS/nixpkgs/issues/92763

If you manage to update lispPackages, that'd be great, but I've been trying for months, and nobody feels the need to help because these knuckleheads haven't tagged anything since last year

**Comment by walseb** [comment]
Thanks! Now we at least know why this isn't working

**Comment by jmercouris** [comment]
There exists a default.nix on master now that allows you to compile master on NixOS! Please let me know if you experience any problems!
