### ISSUE TITLE
Disable help-mode when leaving help  buffers

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#863]
Current if we navigate from a help buffer to a non-help buffer (e.g. by opening a URL) help-mode remains enable.  For now this is benign, but in the future it may have undesirable side effects.

A possible fix would be to add a resource-request handler to disable help mode on the next navigation.

See also #745 for a discussion on how to deal with local schemes like `lisp://` or `nyxt://`.  Maybe this could help here.

**Comment by jmercouris** [comment]
Since help buffers will likely be internal-buffers in subsequent versions of the code, I suggest the following:

+ one can not change the URL of a help buffer
+ invoking set-url in a help buffer or clicking a link, or attempting to access any external resource should result in the creation and focus of a new non internal-buffer

thoughts?

**Comment by Ambrevar** [comment]
> + one can not change the URL of a help buffer

Disagreed: the URL could be that of another help buffer, e.g. when
clicking on a cross reference or calling `C-space set-url RET nyxt://whateverlisp...`

> + invoking set-url in a help buffer or clicking a link, or attempting to access any external resource should result in the creation and focus of a new non internal-buffer

Agreed.

**Comment by jmercouris** [comment]
Ah, if you consider the Nyxt:// protocol, then yes, I agree!

**Comment by jmercouris** [comment]
This is now fixed since all help buffers are internal buffers.
