### ISSUE TITLE
Protect against IDN homograph attacks

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#915]
See https://webkitgtk.org/reference/webkit2gtk/stable/webkit2gtk-4.0-WebKitURIUtilities.html

**Comment by aartaka** [comment]
I may misunderstand here, but Nyxt seems to be safe from homograph attacks because IDN links are _always_ shown to user as Punycode (tested on Russian [профстажировки.рф](https://xn--80aeliblxdekein0a.xn--p1ai/), [точкабудущего.рф](https://xn--80acgdf0a1ag2aob6b6a.xn--p1ai/), [единыйурок.рф](https://www.xn--d1abkefqip0a2f.xn--p1ai/), [сайтыобразованию.рф](https://xn--80aaacg3ajc5bedviq9k9b.xn--p1ai/) which seem to be at least relatively reliable). 

Using this utility function to render URLs can anyways be more solid than the home-grown solution, because, probably, people working on WebKitGTK have taken more things in consideration and had more time to polish it :)

**Comment by Ambrevar** [comment]
You are true, Puny code is used, so there is no security concern here.
It's only a matter of cosmetic and usability.  So we need an FFI binding
to webkit_uri_for_display.

**Comment by Ambrevar** [comment]
Fixed in f9ef1a8b06cae0d757f26114173631e25c24ed0d.
