### ISSUE TITLE
Remove *default-proxy*?

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nyxt#935]
Does not seem it's useful anymore now that it's so easy to customize the `proxy` slot of `proxy-mode`.

**Comment by Ambrevar** [comment]
Similarly we should probably move the `auto-mode:*prompt-on-mode-toggle*` `auto-mode:*non-rememberable-modes*` globals to auto-mode slots.  @aartaka Thoughts on this?

**Comment by jmercouris** [comment]
@aartaka ?

**Comment by aartaka** [comment]
Sorry, I somewhy disabled notifications for mentions xD 

It sounds good to me. Given that the only use-case for modifying these auto-mode globals is in init file, it won't hurt anyone in runtime, I believe.

**Comment by Ambrevar** [comment]
I've moved *default-proxy* to a slot in 
6582d615d484037cee3c360c6d8ae25ba0492c71.

However I haven't move the globals in auto-mode because they are
semantically truly
global, not mode-local.

For instance `*non-rememberable-modes*` is used in
`non-rememberable-mode-p` which is used in `rememberable-of` which is
used in the `enable-matching-modes`...  There is no auto-mode all the
way.

Regarding `*prompt-on-mode-toggle*`, it's dynamically bound at some
point.  It's possible to simulate dynamic slot bindings with
unwind-protect, but that's not very convenient.  Maybe there is a
generic, clean way to do this.

I can see two solutions:

- Turn `*non-rememberable-modes*` and `*prompt-on-mode-toggle*` into a
  user class with a single slot.  This gives us graphical configuration
  and access to the original value.

- Or add a `current-auto-mode` function which returns the auto-mode in
  context.

  This function could be implemented as (find-submode (current-buffer) 'auto-mode).

Thoughts?

**Comment by aartaka** [comment]
> However I haven't move the globals in auto-mode because they are semantically truly global, not mode-local. For instance `*non-rememberable-modes*` is used in `non-rememberable-mode-p` which is used in `rememberable-of` which is used in the `enable-matching-modes`... There is no auto-mode all the way. 

That's true, but both `non-rememberable-mode-p` and `rememberable-of` are one-liners and can be easily rewritten/`flet`-bound (latter appeals more to me, because domain of application is quite restricted for these functions) to use `auto-mode` instances.

> Regarding `*prompt-on-mode-toggle*`, it's dynamically bound at some point. It's possible to simulate dynamic slot bindings with unwind-protect, but that's not very convenient. Maybe there is a generic, clean way to do this.

Another option: turn `*prompt-on-mode-toggle*` into `auto-mode` slot and refer to it in `initialize-auto-mode` (instead of dynamic binding in `make-mode-toggle-prompting-handler`), adding prompting handlers only if it's `t`. It was working this way in one of the initial iterations of `auto-mode` (in [`53866c1`](https://github.com/atlas-engineer/nyxt/blob/53866c14f7f0ae824c3553614707aefd8b913a18/source/auto-mode.lisp#L92), for example) and it fits well into this global-less change, I believe. 

> - Or add a `current-auto-mode` function which returns the auto-mode in context. This function could be implemented as (find-submode (current-buffer) 'auto-mode). 

Sounds like reinventing `user-*` classes. I'm sure we can do it all as slots of `auto-mode` and we won't need to spawn anything else :)

**Comment by Ambrevar** [comment]
Thanks for your feedback.  Could you send a patch if you've got the time?

**Comment by aartaka** [comment]
Sure I could :)
