### ISSUE TITLE
Default bindings are not totally "emacsy"

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#950]
Hi nyxt,

I'm wondering why the default bindings differ so much from Emacs.  For instance:

- C-SPC is M-x.

- the C-h prefix should be equivalent to f1.

- C-g is follow-hint instead of `keyboard-quit`

- search-buffer is C-f instead of C-s.

You get the point. I know I can rebind everything, but since nyxt follows the "emacs way of things", my first experience seems a bit off from what I'd expect.

**Comment by aartaka** [comment]
Default bindings mimic CUA scheme (because it's more widespread), as far as I know. If you want to enable Emacsy keybindings, you should add `emacs-mode` to your `default-modes`, i.e.
``` lisp
(define-configuration buffer
  ((default-modes (append '(emacs-mode) %slot-default))))
```

And all the keybindings (`C-h`, `C-s`, `M-x` are certainly there, I remember using them when in `emacs-mode`) you described will be there!

I guess Nyxt follows Emacs in being immensely customizable in the first place. And, as Emacs has EVIL and CUA modes available, Nyxt has several different keybinding schemes. CUA may be unobvious for Emacs users, but that's still what most users will make sense of. It's a trade-off that was necessary to make using Nyxt easier for newcomers.

**Comment by aadcg** [comment]
Artyom Bologov <notifications@github.com> writes:

> Default bindings mimic CUA scheme (because it's more widespread), as far
> as I know. If you want to enable Emacsy keybindings, you should add
> emacs-mode to your default-modes, i.e.
>
> (define-configuration buffer
>   ((default-modes (append '(emacs-mode) %slot-default))))

Oh, I'm sorry, I was unaware of this emacs-mode!  Silly me who missed
this bit in the documentation.

> And all the keybindings (C-h, C-s, M-x are certainly there, I remember
> using them when in emacs-mode) you described will be there!
>
> I guess Nyxt follows Emacs in being immensely customizable in the first
> place. And, as Emacs has EVIL and CUA modes available, Nyxt has several
> different keybinding schemes. CUA may be unobvious for Emacs users, but
> that's still what most users will make sense of. It's a trade-off that
> was necessary to make using Nyxt easier for newcomers.

I get the point, and I find reasonable.  My concern was that there was
no "emacs" experience out of the box.

Thanks for this amazing project.
