### ISSUE TITLE
Init file isn't honored in all buffers

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#975]
After updating to `nyxt 2-pre-release-2`, available from `guix`, it seems that the init file is only respect in the scratch buffer. For instance, I use `emacs-mode` but as soon as I open another url the mode isn't set by default anymore. 

It seems I'm missing something basic. Perhaps there was a recent change that I'm not aware of...

```lisp
(defvar *my-keymap* (make-keymap "my-map"))
(define-key *my-keymap*
  "C-j" 'nyxt/web-mode:follow-hint
  "C-J" 'nyxt/web-mode:follow-hint-new-buffer
  "C-u C-J" 'nyxt/web-mode:follow-hint-new-buffer-focus
  "C-x C-b" 'nyxt:list-buffers)

(define-mode my-mode ()
  "Dummy mode for the custom key bindings in `*my-keymap*'."
  ((keymap-scheme :initform (keymap:make-scheme
                             scheme:emacs *my-keymap*))))

(define-configuration buffer
  ((default-modes (append '(emacs-mode my-mode) %slot-default))
   (current-zoom-ratio 1.75)
   (zoom-ratio-default 1.75)
   ))
```

**Comment by Ambrevar** [comment]
Indeed, since pre-release-2 we now have 3 kinds of buffers:

- buffers (a virtual class)
- internal-buffers used for the pages, everything specific to Nyxt.
- web-buffers used, well, for web pages!

Inheritance works, so if you configure a slot for BUFFERS it will be
forwarded to `web-buffer` and `internal-buffer`.  Unless(!) the slot is
already specialized by the child class.

The `web-buffer` class specializes default-modes, which is why setting
the default-modes slot in `buffer` won't reflect on web-buffers.

If you want to use my-mode and emacs-mode in both internal-buffers and
web-buffers, you must configure both classes:

(define-configuration (buffer web-buffer)
    ((default-modes (append '(emacs-mode my-mode) %slot-default))
     (current-zoom-ratio 1.75)
     (zoom-ratio-default 1.75)))

The manual is out-of-date, I'll fix it just now.

**Comment by aadcg** [comment]
I see, thanks!

**Comment by Ambrevar** [comment]
Documentation updated in 98a6a07f9bc17b0d61fa08df584f76921e7e7dfc.

**Comment by aadcg** [comment]
Looks good to me. Thanks again.
