### ISSUE TITLE
Integration with Emacs (eww)

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nyxt#993]
This is just for future reference, or we could discuss if it makes sense to be integrated in the documention or elsewhere. Emacs users frequently use eww and make use of `eww-browse-with-external-browser`.  The following snippet sets everything in place so that users can open the current url externally with Nyxt. By default, it's bound to `&`.

```
(setq browse-url-secondary-browser-function 'browse-url-generic)
(setq browse-url-generic-program "nyxt")
```

Also, if you're using sway and you had a hard time to assign Nyxt to a certain workspace, it seems that the only possible way is the following (add it to ~/.config/sway/config)

```
assign [app_id="sbcl"] the-name-of-the-workspace
```

**Comment by Ambrevar** [comment]
Thanks for sharing!

I'm not sure this belongs to the Nyxt documentation because really it's
an Emacs setting.  Many programs can set a favourite browser and I'm not
sure it's reasonable for us to document them all.

For Sway (or any WM with workspaces), the class name of Nyxt is `sbcl`
and `nyxt` while the window title always starts with `Nyxt -`.

**Comment by jmercouris** [comment]
I concur with Pierre. This is a really good to know thing, but it is not really about Nyxt. It is about Nyxt's integration with something else. Sure, we are all Emacs users, but yeah :-D

Thank you for the idea here! Even just opening this issue is a great step towards figuring out how we may integrate this information AND help other users in the future who might be wondering the same thing.

**Comment by aadcg** [comment]
I agree with both of you!  I started this "issue" so that users would find this information right away in case they will skim through on github.
